// GENERATED by service/tools/sync_catalogue.mjs from game/config/catalogue.json.
// Do not edit: change the JSON and run `node tools/sync_catalogue.mjs`.
export default {
 "_comment": "Ultimate Trifecta authoritative catalogue (V6). One source for previews, ownership, Shop, Season Pass, saves, networking and the service. Item IDs are stable and never reused: runner items are '<Cosmetics field>:<Cosmetics key>' (the same strings the save's owned list has used since V3), profile cosmetics 'card:<key>' / 'badge:<key>', coin packs 'coins:<n>', Season premium 'season:<id>:premium'. Real-money prices are never stored here: the Shop shows StoreKit's localized price. The service copy (service/src/catalogue_data.js) is generated from this file by service/tools/sync_catalogue.mjs and a test fails if they differ.",
 "catalogue_version": 1,
 "bundle_prefix": "com.idlery.ultimatetrifecta",
 "products": {
  "com.idlery.ultimatetrifecta.coins.500": {
   "kind": "coin_pack",
   "item": "coins:500",
   "coins": 500,
   "apple_type": "CONSUMABLE",
   "reference_name": "Coins 500"
  },
  "com.idlery.ultimatetrifecta.coins.1500": {
   "kind": "coin_pack",
   "item": "coins:1500",
   "coins": 1500,
   "apple_type": "CONSUMABLE",
   "reference_name": "Coins 1500"
  },
  "com.idlery.ultimatetrifecta.coins.3500": {
   "kind": "coin_pack",
   "item": "coins:3500",
   "coins": 3500,
   "apple_type": "CONSUMABLE",
   "reference_name": "Coins 3500"
  },
  "com.idlery.ultimatetrifecta.skin.moonlight_runner": {
   "kind": "apple_skin",
   "item": "outfit:moonlight_runner",
   "apple_type": "NON_CONSUMABLE",
   "reference_name": "Skin Moonlight Runner"
  },
  "com.idlery.ultimatetrifecta.skin.starry_sleeper": {
   "kind": "apple_skin",
   "item": "outfit:starry_sleeper",
   "apple_type": "NON_CONSUMABLE",
   "reference_name": "Skin Starry Sleeper"
  }
 },
 "items": [
  {
   "id": "outfit:moonlight_runner",
   "kind": "apple_skin",
   "product": "com.idlery.ultimatetrifecta.skin.moonlight_runner",
   "featured": 1,
   "blurb": "A night-run outfit for 3 a.m. sprints across the quad. Yours to keep, restorable on any device signed in to your Apple Account."
  },
  {
   "id": "outfit:starry_sleeper",
   "kind": "apple_skin",
   "product": "com.idlery.ultimatetrifecta.skin.starry_sleeper",
   "featured": 2,
   "blurb": "Starry sleepwear for the cosiest runner on campus. Yours to keep, restorable on any device signed in to your Apple Account."
  },
  {
   "id": "outfit:lantern_scout",
   "kind": "coin_item",
   "price": 1200,
   "featured": 3,
   "blurb": "Lantern Scout: ready for the darkest corner of campus."
  },
  {
   "id": "outfit:campus_courier",
   "kind": "coin_item",
   "price": 900,
   "blurb": "Campus Courier: every shortcut, every night."
  },
  {
   "id": "outfit:raincoat_explorer",
   "kind": "coin_item",
   "price": 800,
   "blurb": "Raincoat Explorer: made for splashing into all three waters."
  },
  {
   "id": "outfit:varsity_sprinter",
   "kind": "coin_item",
   "price": 600,
   "blurb": "Varsity Sprinter: team colours for the run home."
  },
  {
   "id": "outfit:frog",
   "kind": "coin_item",
   "price": 500,
   "legacy": true
  },
  {
   "id": "outfit:duck",
   "kind": "coin_item",
   "price": 450,
   "legacy": true
  },
  {
   "id": "outfit:robe",
   "kind": "coin_item",
   "price": 300,
   "legacy": true
  },
  {
   "id": "pattern:pinstripes",
   "kind": "coin_item",
   "price": 40,
   "legacy": true
  },
  {
   "id": "pattern:bands",
   "kind": "coin_item",
   "price": 40,
   "legacy": true
  },
  {
   "id": "color:navy",
   "kind": "coin_item",
   "price": 30,
   "legacy": true
  },
  {
   "id": "color:mint",
   "kind": "coin_item",
   "price": 30,
   "legacy": true
  },
  {
   "id": "color:coral",
   "kind": "coin_item",
   "price": 30,
   "legacy": true
  },
  {
   "id": "color:plum",
   "kind": "coin_item",
   "price": 30,
   "legacy": true
  },
  {
   "id": "trim:navy",
   "kind": "coin_item",
   "price": 20,
   "legacy": true
  },
  {
   "id": "trim:pink",
   "kind": "coin_item",
   "price": 20,
   "legacy": true
  },
  {
   "id": "trim:gold",
   "kind": "coin_item",
   "price": 20,
   "legacy": true
  },
  {
   "id": "hair_color:blue",
   "kind": "coin_item",
   "price": 40,
   "legacy": true
  },
  {
   "id": "hair_color:pink",
   "kind": "coin_item",
   "price": 40,
   "legacy": true
  },
  {
   "id": "hat:party",
   "kind": "coin_item",
   "price": 60,
   "legacy": true
  },
  {
   "id": "hat:headphones",
   "kind": "coin_item",
   "price": 110,
   "legacy": true
  },
  {
   "id": "hat:crown",
   "kind": "coin_item",
   "price": 240,
   "legacy": true
  },
  {
   "id": "shoes:sneakers",
   "kind": "coin_item",
   "price": 50,
   "legacy": true
  },
  {
   "id": "shoes:flippers",
   "kind": "coin_item",
   "price": 130,
   "legacy": true
  },
  {
   "id": "emote:dance",
   "kind": "coin_item",
   "price": 80,
   "legacy": true
  },
  {
   "id": "coins:500",
   "kind": "coin_pack",
   "product": "com.idlery.ultimatetrifecta.coins.500",
   "coins": 500
  },
  {
   "id": "coins:1500",
   "kind": "coin_pack",
   "product": "com.idlery.ultimatetrifecta.coins.1500",
   "coins": 1500
  },
  {
   "id": "coins:3500",
   "kind": "coin_pack",
   "product": "com.idlery.ultimatetrifecta.coins.3500",
   "coins": 3500
  },
  {
   "id": "season:s1:premium",
   "kind": "season_premium",
   "season": "s1",
   "price": 1500,
   "name": "Season 1 · After Hours Premium",
   "blurb": "Unlocks the Premium track of Season 1 · After Hours for this season, permanently. Every Premium reward you have already earned becomes claimable at once. It never changes speed, reach, stealth or score, it isn't a subscription, and it doesn't skip tiers."
  },
  {
   "id": "outfit:after_hours_hoodie",
   "kind": "season_reward",
   "season": "s1"
  },
  {
   "id": "outfit:night_owl",
   "kind": "season_reward",
   "season": "s1"
  },
  {
   "id": "outfit:glow_jogger",
   "kind": "season_reward",
   "season": "s1"
  },
  {
   "id": "outfit:library_cardigan",
   "kind": "season_reward",
   "season": "s1"
  },
  {
   "id": "hat:headlamp",
   "kind": "season_reward",
   "season": "s1"
  },
  {
   "id": "hat:pompom_beanie",
   "kind": "season_reward",
   "season": "s1"
  },
  {
   "id": "hat:glow_headband",
   "kind": "season_reward",
   "season": "s1"
  },
  {
   "id": "hat:owl_ears",
   "kind": "season_reward",
   "season": "s1"
  },
  {
   "id": "shoes:glow_sneakers",
   "kind": "season_reward",
   "season": "s1"
  },
  {
   "id": "shoes:moon_boots",
   "kind": "season_reward",
   "season": "s1"
  },
  {
   "id": "emote:stargaze",
   "kind": "season_reward",
   "season": "s1"
  },
  {
   "id": "emote:victory_lap",
   "kind": "season_reward",
   "season": "s1"
  },
  {
   "id": "emote:shush",
   "kind": "season_reward",
   "season": "s1"
  },
  {
   "id": "emote:moon_shuffle",
   "kind": "season_reward",
   "season": "s1"
  },
  {
   "id": "card:after_hours",
   "kind": "season_reward",
   "season": "s1",
   "profile": "card",
   "name": "After Hours",
   "colors": [
    "17305a",
    "1f6f73"
   ],
   "accent": "ffc65c"
  },
  {
   "id": "card:moonlit_quad",
   "kind": "season_reward",
   "season": "s1",
   "profile": "card",
   "name": "Moonlit Quad",
   "colors": [
    "1d2a52",
    "6b7fa8"
   ],
   "accent": "e7ecf5"
  },
  {
   "id": "card:dawn_patrol",
   "kind": "season_reward",
   "season": "s1",
   "profile": "card",
   "name": "Dawn Patrol",
   "colors": [
    "4a2b5c",
    "c9776a"
   ],
   "accent": "ffd9a8"
  },
  {
   "id": "card:lantern_glow",
   "kind": "season_reward",
   "season": "s1",
   "profile": "card",
   "name": "Lantern Glow",
   "colors": [
    "4a2a12",
    "c7782a"
   ],
   "accent": "ffe0a3"
  },
  {
   "id": "card:starfield",
   "kind": "season_reward",
   "season": "s1",
   "profile": "card",
   "name": "Starfield",
   "colors": [
    "141a3d",
    "32306e"
   ],
   "accent": "f6f3ec",
   "stars": true
  },
  {
   "id": "card:library_lamp",
   "kind": "season_reward",
   "season": "s1",
   "profile": "card",
   "name": "Library Lamp",
   "colors": [
    "173b2e",
    "4f6b3a"
   ],
   "accent": "e8c779"
  },
  {
   "id": "card:glow_track",
   "kind": "season_reward",
   "season": "s1",
   "profile": "card",
   "name": "Glow Track",
   "colors": [
    "0f3c45",
    "3f8f5a"
   ],
   "accent": "c9f27a"
  },
  {
   "id": "card:night_sky",
   "kind": "season_reward",
   "season": "s1",
   "profile": "card",
   "name": "Night Sky",
   "colors": [
    "0b1028",
    "4b2f7a"
   ],
   "accent": "b9a6ff",
   "stars": true
  },
  {
   "id": "badge:first_splash",
   "kind": "season_reward",
   "season": "s1",
   "profile": "badge",
   "name": "First Splash",
   "icon": "drop",
   "color": "5fd6c8"
  },
  {
   "id": "badge:night_shift",
   "kind": "season_reward",
   "season": "s1",
   "profile": "badge",
   "name": "Night Shift",
   "icon": "whistle",
   "color": "ffa05c"
  },
  {
   "id": "badge:s1_finisher",
   "kind": "season_reward",
   "season": "s1",
   "profile": "badge",
   "name": "Season 1 Finisher",
   "icon": "star",
   "color": "ffc65c"
  },
  {
   "id": "badge:lantern",
   "kind": "season_reward",
   "season": "s1",
   "profile": "badge",
   "name": "Lantern",
   "icon": "lantern",
   "color": "ffc65c"
  },
  {
   "id": "badge:crescent_moon",
   "kind": "season_reward",
   "season": "s1",
   "profile": "badge",
   "name": "Crescent Moon",
   "icon": "moon",
   "color": "e7ecf5"
  },
  {
   "id": "badge:owl",
   "kind": "season_reward",
   "season": "s1",
   "profile": "badge",
   "name": "Night Owl",
   "icon": "owl",
   "color": "c9a26b"
  },
  {
   "id": "badge:gold_lantern",
   "kind": "season_reward",
   "season": "s1",
   "profile": "badge",
   "name": "Gold Lantern",
   "icon": "lantern",
   "color": "ffd76e"
  },
  {
   "id": "badge:trifecta_star",
   "kind": "season_reward",
   "season": "s1",
   "profile": "badge",
   "name": "Trifecta Star",
   "icon": "star",
   "color": "5fd6c8"
  }
 ],
 "seasons": {
  "s1": {
   "number": 1,
   "name": "After Hours",
   "premium_item": "season:s1:premium",
   "starts_at": null,
   "ends_at": null,
   "_dates": "Season dates are server UTC and deliberately unset for this beta: no countdown is shown and purchased access never expires. Earned and claimed rewards are permanent.",
   "tiers": [
    {
     "tier": 1,
     "xp": 0,
     "free": {
      "item": "card:after_hours"
     },
     "premium": {
      "item": "outfit:night_owl"
     }
    },
    {
     "tier": 2,
     "xp": 200,
     "free": null,
     "premium": {
      "coins": 50
     }
    },
    {
     "tier": 3,
     "xp": 400,
     "free": {
      "item": "hat:pompom_beanie"
     },
     "premium": {
      "item": "badge:lantern"
     }
    },
    {
     "tier": 4,
     "xp": 600,
     "free": null,
     "premium": {
      "item": "emote:shush"
     }
    },
    {
     "tier": 5,
     "xp": 800,
     "free": {
      "coins": 25
     },
     "premium": {
      "item": "card:lantern_glow"
     }
    },
    {
     "tier": 6,
     "xp": 1000,
     "free": null,
     "premium": {
      "coins": 50
     }
    },
    {
     "tier": 7,
     "xp": 1200,
     "free": {
      "item": "badge:first_splash"
     },
     "premium": {
      "item": "hat:headlamp"
     }
    },
    {
     "tier": 8,
     "xp": 1400,
     "free": null,
     "premium": {
      "item": "badge:crescent_moon"
     }
    },
    {
     "tier": 9,
     "xp": 1600,
     "free": {
      "item": "emote:stargaze"
     },
     "premium": {
      "coins": 50
     }
    },
    {
     "tier": 10,
     "xp": 1800,
     "free": null,
     "premium": {
      "item": "shoes:glow_sneakers"
     }
    },
    {
     "tier": 11,
     "xp": 2100,
     "free": {
      "coins": 25
     },
     "premium": {
      "item": "card:starfield"
     }
    },
    {
     "tier": 12,
     "xp": 2400,
     "free": null,
     "premium": {
      "coins": 50
     }
    },
    {
     "tier": 13,
     "xp": 2700,
     "free": {
      "item": "card:moonlit_quad"
     },
     "premium": {
      "item": "badge:owl"
     }
    },
    {
     "tier": 14,
     "xp": 3000,
     "free": null,
     "premium": {
      "item": "hat:owl_ears"
     }
    },
    {
     "tier": 15,
     "xp": 3300,
     "free": {
      "item": "outfit:after_hours_hoodie"
     },
     "premium": {
      "item": "outfit:glow_jogger"
     }
    },
    {
     "tier": 16,
     "xp": 3600,
     "free": null,
     "premium": {
      "coins": 50
     }
    },
    {
     "tier": 17,
     "xp": 3900,
     "free": {
      "item": "badge:night_shift"
     },
     "premium": {
      "item": "card:library_lamp"
     }
    },
    {
     "tier": 18,
     "xp": 4200,
     "free": null,
     "premium": {
      "item": "emote:moon_shuffle"
     }
    },
    {
     "tier": 19,
     "xp": 4500,
     "free": {
      "item": "shoes:moon_boots"
     },
     "premium": {
      "coins": 50
     }
    },
    {
     "tier": 20,
     "xp": 4800,
     "free": null,
     "premium": {
      "item": "badge:gold_lantern"
     }
    },
    {
     "tier": 21,
     "xp": 5150,
     "free": {
      "coins": 50
     },
     "premium": {
      "item": "card:glow_track"
     }
    },
    {
     "tier": 22,
     "xp": 5500,
     "free": null,
     "premium": {
      "coins": 50
     }
    },
    {
     "tier": 23,
     "xp": 5850,
     "free": {
      "item": "hat:glow_headband"
     },
     "premium": {
      "item": "badge:trifecta_star"
     }
    },
    {
     "tier": 24,
     "xp": 6200,
     "free": null,
     "premium": {
      "coins": 50
     }
    },
    {
     "tier": 25,
     "xp": 6550,
     "free": {
      "item": "card:dawn_patrol"
     },
     "premium": {
      "item": "card:night_sky"
     }
    },
    {
     "tier": 26,
     "xp": 6900,
     "free": null,
     "premium": {
      "coins": 50
     }
    },
    {
     "tier": 27,
     "xp": 7250,
     "free": {
      "item": "emote:victory_lap"
     },
     "premium": {
      "coins": 50
     }
    },
    {
     "tier": 28,
     "xp": 7600,
     "free": null,
     "premium": {
      "coins": 50
     }
    },
    {
     "tier": 29,
     "xp": 7950,
     "free": null,
     "premium": {
      "coins": 50
     }
    },
    {
     "tier": 30,
     "xp": 8300,
     "free": {
      "item": "badge:s1_finisher"
     },
     "premium": {
      "item": "outfit:library_cardigan"
     }
    }
   ]
  }
 },
 "economy": {
  "_comment": "Centralised earning values (client projection and service settlement read the same numbers). Coins and Season XP come only from eligible, service-verified online rounds; practice settles nothing into the wallet or the pass. Purchased Coins never become XP.",
  "round_coins": {
   "completed": 10,
   "team_win": 4,
   "runner_home": 3,
   "first_home": 2,
   "watch_distinct_tag": 1,
   "watch_distinct_tag_cap": 3,
   "pickup": 1
  },
  "season_xp": {
   "completed": 50,
   "stamp": 10,
   "stamp_cap": 3,
   "runner_home": 20,
   "team_win": 15,
   "watch_distinct_tag": 15,
   "watch_distinct_tag_cap": 3
  },
  "eligibility": {
   "min_humans": 2,
   "present_share": 0.6,
   "min_round_s": 60,
   "max_round_s": 900,
   "report_window_s": 1200,
   "ack_window_s": 604800,
   "max_coin_spawns": 10,
   "daily_round_cap": 40
  },
  "legacy_import": {
   "cap": 2000,
   "per_online_round": 75,
   "per_practice_round": 38
  },
  "challenges": {
   "_comment": "Pass 8: daily and weekly goals that add Season XP to the existing pass (no other currency, no boost, nothing to buy, no claim button). Progress comes only from eligible, service-verified, completed online rounds the player actively played (active_s: seconds of real input or objective play counted by the host's simulation; a round is active when active_s >= min(active.min_s, active.min_share x round time)). A round belongs to the UTC day (00:00 UTC) and week (Monday 00:00 UTC) of its registered start and can settle into that period until grace_s after the period ends. Contribution credits: each unique required-water stamp or each different runner tagged, at most credit_cap_per_round a round. Bonus XP is added in the round's settlement, once per player and challenge instance.",
   "version": 1,
   "grace_s": 86400,
   "credit_cap_per_round": 3,
   "active": {
    "min_s": 60,
    "min_share": 0.4,
    "window_s": 5
   },
   "daily": [
    {
     "id": "night_shift",
     "name": "Night Shift",
     "task": "Play 2 online rounds",
     "metric": "active_rounds",
     "goal": 2,
     "xp": 50
    },
    {
     "id": "campus_contribution",
     "name": "Campus Contribution",
     "task": "Earn 6 contribution credits",
     "metric": "credits",
     "goal": 6,
     "xp": 50
    },
    {
     "id": "team_effort",
     "name": "Team Effort",
     "task": "Win 1 round, either role",
     "metric": "round_wins",
     "goal": 1,
     "xp": 50
    }
   ],
   "weekly": [
    {
     "id": "campus_regular",
     "name": "Campus Regular",
     "task": "Play 10 online rounds",
     "metric": "active_rounds",
     "goal": 10,
     "xp": 150
    },
    {
     "id": "pull_your_weight",
     "name": "Pull Your Weight",
     "task": "Earn 18 contribution credits",
     "metric": "credits",
     "goal": 18,
     "xp": 150
    },
    {
     "id": "strong_together",
     "name": "Strong Together",
     "task": "Win 4 rounds, either role",
     "metric": "round_wins",
     "goal": 4,
     "xp": 150
    }
   ]
  }
 }
};
