// GENERATED by tools/build_terms.py: edit the lists there.
// 
// Slurs, sexual terms and profanity are stored base64-encoded so the source
// does not spell them out.  SUBSTRING lists match inside the name's skeleton
// (lowercase, leet digits mapped, separators removed, repeated letters
// collapsed) after harmless ALLOW words are cut out; *_TOKENS lists match only
// whole words (split on spaces, underscores, digits and lower->Upper changes).
export const SLURS = ["bmlnZ2Vy", "bmlnZ2E=", "bmlnYQ==", "ZmFnZ290", "ZmFnb3Q=", "ZmFnZ2l0", "cmV0YXJk", "dHJhbm55", "a2lrZQ==", "Y2hpbms=", "Z29vaw==", "d2V0YmFjaw==", "YmVhbmVy", "dG93ZWxoZWFk", "Y29vbg==", "ZHlrZQ==", "cGFraQ==", "cmFnaGVhZA=="];
export const SLUR_TOKENS = ["ZmFn", "ZmFncw==", "c3BpYw==", "c3BpY2s=", "amFw", "amFwcw==", "aG9tbw==", "bmVncm8=", "bmln", "Z3lw", "Z3lwc3k="];
export const SEXUAL = ["cG9ybg==", "cGVuaXM=", "dmFnaW5h", "cHVzc3k=", "aG9ybnk=", "bnVkZQ==", "bmFrZWQ=", "aGVudGFp", "bWlsZg==", "b25seWZhbnM=", "Ymxvd2pvYg==", "aGFuZGpvYg==", "ZGlsZG8=", "b3JnYXNt", "Ym9vYg==", "ZXJvdGlj", "ZmV0aXNo", "cmFwaXN0", "cmFwZQ==", "bW9sZXN0", "cGVkbw==", "aW5jZXN0", "c2V4eQ==", "c2V4", "aml6eg==", "Y2xpdA==", "dGl0dHk=", "Y29jaw==", "ZGljaw==", "YnV0dGhvbGU=", "bmlwcGxl", "eHh4", "Ym9uZXI=", "aG9ybmk="];
export const SEXUAL_TOKENS = ["Y3Vt", "YW5hbA==", "dGl0cw==", "dGl0", "YXNz", "YnV0dA==", "bnNmdw==", "bGV3ZA==", "eHh4", "c2V4eA=="];
export const PROFANITY = ["ZnVjaw==", "ZmNr", "ZnVr", "c2hpdA==", "Yml0Y2g=", "Y3VudA==", "d2hvcmU=", "c2x1dA==", "YmFzdGFyZA==", "YXNzaG9sZQ==", "bW90aGVyZg==", "d2Fua2Vy", "dHdhdA==", "cHJpY2s=", "Ym9sbG9jaw==", "YXJzZQ==", "cGlzcw==", "ZG91Y2hl", "ZGFtbWl0"];
export const THREATS = ["kys", "killyou", "killurself", "killyourself", "killself", "suicide", "murder", "shootup", "terrorist", "nazi", "hitler", "genocide", "diedie", "kms"];
export const THREAT_TOKENS = ["kill", "shoot", "stab"];
export const STAFF = ["admin", "moderator", "staff", "official", "support", "developer", "trifecta", "nightwatch", "system", "gamecenter", "idlery", "helpdesk", "customerservice"];
export const STAFF_TOKENS = ["mod", "mods", "dev", "devs", "bot", "gm", "cm", "apple", "owner"];
export const CONTACT = ["http", "www", "discord", "snapchat", "instagram", "tiktok", "telegram", "whatsapp", "twitter", "youtube", "twitch", "paypal", "venmo", "cashapp", "gmail", "yahoo", "hotmail", "icloud", "callme", "dmme", "addme", "textme", "followme"];
export const CONTACT_TOKENS = ["com", "net", "org", "gg", "io", "ttv", "yt", "ig", "fb", "kik", "snap", "insta", "email", "dm", "tel", "www", "http", "https"];
export const ALLOW = ["scunthorpe", "cocktail", "cockatoo", "peacock", "hancock", "hitchcock", "woodcock", "shuttlecock", "cockpit", "dickens", "dickinson", "benedick", "dickey", "dicky", "chickadee", "grape", "drape", "scrape", "trapeze", "parapet", "therapist", "therapy", "skyscraper", "raccoon", "cocoon", "tycoon", "sussex", "essex", "middlesex", "sexton", "sextant", "sextet", "badminton", "staffy", "pussycat", "pussywillow", "boobook", "booboo", "arsenal", "arsenic", "parse", "sparse", "coarse", "hoarse", "rehearse", "mississippi", "pistachio", "prickly", "torpedo", "pedometer", "speedo", "bombastic", "bombadil", "bombay", "bomber", "pakistan", "nigeria", "niger", "snigger", "nigel", "spice", "spicy", "kikimora", "japan", "japanese", "cassandra", "dyson", "shiitake", "titan", "titanic", "constitution", "button", "cucumber", "document", "scum", "watch", "swatch", "twatchet", "cocky", "cockroach", "cockney", "cockle", "cockerel", "thorny", "thornier", "thorniest", "entity", "identity", "quantity", "penistone", "shitake", "marseille", "therapeutic", "retardant", "skys"];
