"""Write the campus registers from the merged layer data.

    python3 tools/campus/registers.py

  docs/campus/EVIDENCE_REGISTER.md   every building and water (and the
                                     landmarks) with its sources, date,
                                     confidence, height basis and open
                                     questions; counts and confidence for the
                                     other layers
  docs/campus/evidence_register.csv  one row per evidenced item, all layers
  docs/campus/CHANGE_REGISTER.md     what differs from the 2022 aerial
                                     (removed, added, replaced, realigned)
  docs/campus/NEUTRAL_NAMES.md       inventory code -> neutral id -> in-game
                                     label -> what was traced for it

Only neutral ids, labels, inventory codes and reference ids appear; the
private crosswalk to real names stays outside the repository.  Every line
written is screened against the private deny list when it is available.
"""
import csv
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
DATA = os.path.join(ROOT, "game", "data", "campus")
DOCS = os.path.join(ROOT, "docs", "campus")
NEUTRAL = os.environ.get("CAMPUS_NEUTRAL", "/home/user/campus_ref/work/neutral_ids.tsv")
sys.path.insert(0, HERE)
import build_data  # noqa: E402

LAYERS = ["buildings", "water", "roads", "paths", "areas", "barriers", "trees", "props", "changes"]


def load(name):
    p = os.path.join(DATA, name + ".json")
    return json.load(open(p))["items"] if os.path.exists(p) else []


def cell(v):
    s = "" if v is None else (", ".join(map(str, v)) if isinstance(v, list) else str(v))
    return s.replace("|", "/").replace("\n", " ").strip()


def main():
    data = {k: load(k) for k in LAYERS}
    gp = load("gameplay")
    deny = build_data.deny_words()
    out = {}

    # ---- evidence register
    md = io.StringIO()
    md.write("# Campus evidence register\n\n")
    md.write("Generated by `tools/campus/registers.py` from `game/data/campus`. One row per traced building and water; ")
    md.write("the other layers are summarised (every item is in `evidence_register.csv`). Sources are reference ids: ")
    md.write("`aerial2022` is the 2022 public-domain orthophoto (0.295 m/px), `plan2023pN` and `wayfinding2026` are the ")
    md.write("georeferenced newer plans, `R###` photos, `V##` video frames and `S##` screenshots in the private reference pack. ")
    md.write("Confidence is the tracer's honest estimate. Nothing here is an exact survey.\n\n")
    counts = {k: len(v) for k, v in data.items()}
    md.write("| Layer | Items | High | Medium | Low | No evidence block |\n|---|---|---|---|---|---|\n")
    for k in LAYERS:
        items = data[k]
        conf = {"high": 0, "medium": 0, "low": 0}
        none = 0
        for it in items:
            ev = it.get("ev")
            if not ev:
                none += 1
                continue
            c = str(ev.get("conf", "")).lower()
            if c in conf:
                conf[c] += 1
        md.write(f"| {k} | {len(items)} | {conf['high']} | {conf['medium']} | {conf['low']} | {none} |\n")
    md.write("\n## Buildings\n\n| Id | Code | Label | Kind | Eave h (m) | Floors | Roof | Confidence | Sources | Basis | Open questions |\n|---|---|---|---|---|---|---|---|---|---|---|\n")
    for b in sorted(data["buildings"], key=lambda x: (x.get("background", False), x["id"])):
        if b.get("background") or b.get("zone") == "context":
            continue
        ev = b.get("ev", {})
        md.write("| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |\n".format(
            b["id"], cell(b.get("ref")), cell(b.get("label")), b.get("kind", ""), b.get("h", ""), b.get("floors", ""),
            cell((b.get("roof") or {}).get("type")) + (" (landmark: %s)" % b["landmark"] if b.get("landmark") else ""),
            cell(ev.get("conf")), cell(ev.get("src")), cell(ev.get("note"))[:300], cell(ev.get("open"))[:300]))
    ctx = [b for b in data["buildings"] if b.get("background") or b.get("zone") == "context"]
    md.write(f"\nBackground buildings beyond the play area (simplified, for the view): {len(ctx)}.\n")
    md.write("\n## Waters\n\n| Id | Code | Label | Kind | Surface / floor (m) | Edge | Objective slot | Confidence | Sources | Open questions |\n|---|---|---|---|---|---|---|---|---|---|\n")
    slots = {}
    for g in gp:
        if g.get("kind") == "objective_pool":
            for i, e in enumerate(g["waters"]):
                for wid in e.get("items", [e["id"]]):
                    slots[wid] = "%d (%s)" % (i, e.get("name", e["id"]))
    for w in sorted(data["water"], key=lambda x: x["id"]):
        ev = w.get("ev", {})
        md.write("| {} | {} | {} | {} | {} / {} | {} | {} | {} | {} | {} |\n".format(
            w["id"], cell(w.get("ref")), cell(w.get("label")), w.get("kind", ""), w.get("surface", ""), w.get("floor", ""),
            cell(w.get("edge")), slots.get(w["id"], "decorative"), cell(ev.get("conf")), cell(ev.get("src")), cell(ev.get("open"))[:300]))
    out[os.path.join(DOCS, "EVIDENCE_REGISTER.md")] = md.getvalue()

    # ---- csv of every evidenced item
    cs = io.StringIO()
    wr = csv.writer(cs)
    wr.writerow(["layer", "id", "ref", "kind", "zone", "conf", "date", "src", "note", "open"])
    for k in LAYERS:
        for it in data[k]:
            ev = it.get("ev") or {}
            if not ev and k in ("trees", "props"):
                continue
            wr.writerow([k, it["id"], cell(it.get("ref")), it.get("kind", ""), it.get("zone", ""), cell(ev.get("conf")),
                         cell(ev.get("date")), cell(ev.get("src")), cell(ev.get("note")), cell(ev.get("open"))])
    out[os.path.join(DOCS, "evidence_register.csv")] = cs.getvalue()

    # ---- change register
    ch = io.StringIO()
    ch.write("# Campus change register (2022 aerial -> October 2026)\n\n")
    ch.write("What the rebuild models differently from the 2022 orthophoto, from the georeferenced 2023 plan, ")
    ch.write("the 2026 wayfinding diagram, photos and video. Future proposals are not built; sites under construction ")
    ch.write("are construction areas, not buildings.\n\n")
    ch.write("| Id | Change | Since | Feature | Confidence | Sources | Note |\n|---|---|---|---|---|---|---|\n")
    for c in sorted(data["changes"], key=lambda x: x["id"]):
        ev = c.get("ev", {})
        ch.write("| {} | {} | {} | {} | {} | {} | {} |\n".format(c["id"], cell(c.get("change") or c.get("kind")), cell(c.get("since")),
                 cell(c.get("feature") or c.get("target") or c.get("ref")), cell(ev.get("conf")), cell(ev.get("src")), cell(ev.get("note") or c.get("note"))[:400]))
    if not data["changes"]:
        ch.write("| (none recorded) | | | | | | |\n")
    out[os.path.join(DOCS, "CHANGE_REGISTER.md")] = ch.getvalue()

    # ---- neutral names
    nn = io.StringIO()
    nn.write("# Neutral names\n\n")
    nn.write("Every feature in the reference inventory has a neutral id and an in-game label. Real names identify the ")
    nn.write("reference subjects only in the private research notes; they are not in the game, its data or its ")
    nn.write("marketing (the private crosswalk is kept outside the repository). The labels are generic descriptions ")
    nn.write("chosen for this game, not the institution's names.\n\n")
    nn.write("| Code | Neutral id | In-game label | Traced as |\n|---|---|---|---|\n")
    by_ref = {}
    for k in ("buildings", "water"):
        for it in data[k]:
            for r in re.split(r"[ ,]+", str(it.get("ref") or "")):
                if r:
                    by_ref.setdefault(r, []).append(it["id"])
    if os.path.exists(NEUTRAL):
        rows = list(csv.reader(open(NEUTRAL), delimiter="\t"))
        for r in rows[1:]:
            if len(r) < 3:
                continue
            code, nid, label = r[0], r[1], r[2]
            traced = by_ref.get(code, [])
            nn.write("| {} | {} | {} | {} |\n".format(code, nid, label, ", ".join(traced[:6]) + (" …" if len(traced) > 6 else "") if traced else "not traced"))
    out[os.path.join(DOCS, "NEUTRAL_NAMES.md")] = nn.getvalue()

    # ---- screen and write
    bad = 0
    for path, text in out.items():
        low = text.lower()
        for w in deny:
            for m in re.finditer(r"\b" + re.escape(w) + r"\b", low):
                bad += 1
                line = low.count("\n", 0, m.start()) + 1
                print("REAL NAME in %s line %d (%s…)" % (os.path.relpath(path, ROOT), line, w[:2]))
    if bad:
        print("not written: %d real-name hit(s)" % bad)
        sys.exit(1)
    os.makedirs(DOCS, exist_ok=True)
    for path, text in out.items():
        with open(path, "w") as fh:
            fh.write(text)
        print("wrote", os.path.relpath(path, ROOT))
    print("counts:", counts)


if __name__ == "__main__":
    main()
