"""Regenerate src/terms.js (moderation word lists).  python3 tools/build_terms.py

Slurs, sexual terms and profanity are stored base64-encoded so the source
does not spell them out.  SUBSTRING lists match inside the name's skeleton
(lowercase, leet digits mapped, separators removed, repeated letters
collapsed) after harmless ALLOW words are cut out; *_TOKENS lists match only
whole words (split on spaces, underscores, digits and lower->Upper changes)."""
import base64, json, os

def enc(words):
    return [base64.b64encode(w.encode()).decode() for w in words]

slurs = ["nigger", "nigga", "niga", "faggot", "fagot", "faggit", "retard", "tranny", "kike", "chink", "gook",
         "wetback", "beaner", "towelhead", "coon", "dyke", "paki", "raghead"]
slur_tokens = ["fag", "fags", "spic", "spick", "jap", "japs", "homo", "negro", "nig", "gyp", "gypsy"]
sexual = ["porn", "penis", "vagina", "pussy", "horny", "nude", "naked", "hentai", "milf", "onlyfans", "blowjob", "handjob",
          "dildo", "orgasm", "boob", "erotic", "fetish", "rapist", "rape", "molest", "pedo", "incest", "sexy", "sex", "jizz",
          "clit", "titty", "cock", "dick", "butthole", "nipple", "xxx", "boner", "horni"]
sexual_tokens = ["cum", "anal", "tits", "tit", "ass", "butt", "nsfw", "lewd", "xxx", "sexx"]
profanity = ["fuck", "fck", "fuk", "shit", "bitch", "cunt", "whore", "slut", "bastard", "asshole", "motherf", "wanker",
             "twat", "prick", "bollock", "arse", "piss", "douche", "dammit"]
threats = ["kys", "killyou", "killurself", "killyourself", "killself", "suicide", "murder", "shootup", "terrorist",
           "nazi", "hitler", "genocide", "diedie", "kms"]
# (no "bomb": the game has a Splash Bomb gadget)
threat_tokens = ["kill", "shoot", "stab"]
staff = ["admin", "moderator", "staff", "official", "support", "developer", "trifecta", "nightwatch", "system",
         "gamecenter", "idlery", "helpdesk", "customerservice"]
staff_tokens = ["mod", "mods", "dev", "devs", "bot", "gm", "cm", "apple", "owner"]
contact = ["http", "www", "discord", "snapchat", "instagram", "tiktok", "telegram", "whatsapp", "twitter", "youtube",
           "twitch", "paypal", "venmo", "cashapp", "gmail", "yahoo", "hotmail", "icloud", "callme", "dmme", "addme",
           "textme", "followme"]
contact_tokens = ["com", "net", "org", "gg", "io", "ttv", "yt", "ig", "fb", "kik", "snap", "insta", "email", "dm", "tel",
                  "www", "http", "https"]
allow = ["scunthorpe", "cocktail", "cockatoo", "peacock", "hancock", "hitchcock", "woodcock", "shuttlecock", "cockpit",
         "dickens", "dickinson", "benedick", "dickey", "dicky", "chickadee", "grape", "drape", "scrape", "trapeze",
         "parapet", "therapist", "therapy", "skyscraper", "raccoon", "cocoon", "tycoon", "sussex", "essex", "middlesex",
         "sexton", "sextant", "sextet", "badminton", "staffy", "pussycat", "pussywillow", "boobook", "booboo",
         "arsenal", "arsenic", "parse", "sparse", "coarse", "hoarse", "rehearse", "mississippi", "pistachio",
         "prickly", "torpedo", "pedometer", "speedo", "bombastic", "bombadil", "bombay", "bomber", "pakistan",
         "nigeria", "niger", "snigger", "nigel", "spice", "spicy", "kikimora", "japan", "japanese", "cassandra",
         "dyson", "shiitake", "titan", "titanic", "constitution", "button", "cucumber", "document", "scum", "watch",
         "swatch", "twatchet",
         # V6: more harmless words (names and chat words) that contain a
         # listed term; each has a false-positive test
         "cocky", "cockroach", "cockney", "cockle", "cockerel", "thorny", "thornier", "thorniest", "entity",
         "identity", "quantity", "penistone", "shitake", "marseille", "therapeutic", "retardant", "skys"]
out = {
    "SLURS": enc(slurs), "SLUR_TOKENS": enc(slur_tokens), "SEXUAL": enc(sexual), "SEXUAL_TOKENS": enc(sexual_tokens),
    "PROFANITY": enc(profanity), "THREATS": threats, "THREAT_TOKENS": threat_tokens, "STAFF": staff,
    "STAFF_TOKENS": staff_tokens, "CONTACT": contact, "CONTACT_TOKENS": contact_tokens, "ALLOW": allow,
}
js = "// GENERATED by tools/build_terms.py: edit the lists there.\n" + "\n".join(__doc__.splitlines()[1:]).replace("\n", "\n// ").join(["// ", "\n"])
for k, v in out.items():
    js += f"export const {k} = {json.dumps(v)};\n"
here = os.path.dirname(os.path.abspath(__file__))
p = os.path.join(here, "..", "src", "terms.js")
open(p, "w").write(js)
print("wrote", p, len(js))

# V6: the game keeps the same lists (game/src/core/moderation_terms.gd) for
# instant feedback and receiver-side checks; the service stays the authority.
gd = ("class_name ModerationTerms\nextends RefCounted\n## GENERATED by service/tools/build_terms.py from the same lists as\n"
      "## service/src/terms.js: edit the lists there and rerun it.  Slurs, sexual\n"
      "## terms and profanity are base64-encoded so the source does not spell them\n"
      "## out (NameRules decodes them once).\n\n")
for k, v in out.items():
    gd += "const %s := %s\n" % (k, json.dumps(v))
g = os.path.join(here, "..", "..", "game", "src", "core", "moderation_terms.gd")
if os.path.isdir(os.path.dirname(g)):
    open(g, "w").write(gd)
    print("wrote", g, len(gd))
