// Copies the authoritative catalogue (game/config/catalogue.json) into the
// Worker as src/catalogue_data.js, so the game and the service read one
// catalogue: item IDs, kinds, Coin prices, App Store product IDs, Season
// tables and economy numbers.  test/catalogue.test.mjs fails when the copy
// is stale.  Usage: node tools/sync_catalogue.mjs [--check]
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, '..', '..', 'game', 'config', 'catalogue.json');
const OUT = join(HERE, '..', 'src', 'catalogue_data.js');

export function render() {
  const data = JSON.parse(readFileSync(SRC, 'utf8'));
  return '// GENERATED by service/tools/sync_catalogue.mjs from game/config/catalogue.json.\n' +
    '// Do not edit: change the JSON and run `node tools/sync_catalogue.mjs`.\n' +
    'export default ' + JSON.stringify(data, null, 1) + ';\n';
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const want = render();
  if (process.argv.includes('--check')) {
    const have = readFileSync(OUT, 'utf8');
    if (have !== want) {
      console.error('src/catalogue_data.js is stale: run node tools/sync_catalogue.mjs');
      process.exit(1);
    }
    console.log('catalogue copy up to date');
  } else {
    writeFileSync(OUT, want);
    console.log('wrote', OUT);
  }
}
