class_name CharacterView
extends Node3D
## The skinned Trifecta runner / Night Watch character (one shared asset:
## assets/characters/runner.glb, generated by tools/character/build_character.py).
## Used identically by gameplay, lobby, wardrobe, home and results.
##
## Presentation only: it shows authoritative/interpolated state and never
## moves gameplay (the gameplay capsule lives in the sim).
##
## Forward convention: at yaw 0 the character faces -Z, the same as the sim's
## yaw (forward = Basis(UP, yaw) * -Z) and Godot cameras.  Use face_toward()
## to turn a character to the camera in menu scenes.
##
## Animation: an AnimationTree built per instance (locomotion blend space with
## speed-matched playback rate, a state Transition for everything else, a
## filtered landing one-shot and a turn-in-place one-shot), advanced manually
## at the end of _process so the state chosen this frame is the pose drawn
## this frame.  CharacterSecondary adds head lag / banking; a spring-bone
## chain moves the nightcap tip.  Face shapes are blend shapes on "base".

const SCENE := preload("res://assets/characters/runner.glb")
const SHADER := preload("res://assets/shaders/character.gdshader")

## m/s at which each locomotion clip is blended in (blend-space positions)
const LOCO_POINTS := {"walk": 2.0, "run": 5.0, "sprint": 7.0}
## metres travelled per 1.0 s clip cycle at rate 1 (from runner_manifest.json;
## tools/character/anims.py LOCO[*].speed).  playback rate = speed / this.
const LOCO_M_PER_CYCLE := {"walk": 0.8, "run": 1.7, "sprint": 2.05}

const OUTFIT_PARTS := {
	"pj_stripes": ["pj"], "pj_plain": ["pj"], "swim": ["swim", "body_skin"], "robe": ["robe", "body_skin"],
	"duck": ["duck"], "frog": ["frog"],
}
const HOOD_OUTFITS := ["duck", "frog"]
const HAT_PARTS := {
	"none": [], "nightcap": ["hat_nightcap"], "swimcap": ["hat_swimcap"], "party": ["hat_party"],
	"headphones": ["hat_headphones"], "crown": ["hat_crown"],
}
const HATS_HIDING_HAIR := ["nightcap", "swimcap"]
const SHOE_PARTS := {"slippers": ["shoe_slippers"], "sneakers": ["shoe_hightops"], "flippers": ["shoe_flippers"]}
const HAIR_BY_SKIN := [Color("4a3222"), Color("2e1e15"), Color("1f1712"), Color("151010"), Color("b8743f")]
const STRIPES_PER_M := 13.0

## state name -> AnimationTree Transition input; xfade seconds into that state
const STATES := {
	"ground": 0.14, "jump": 0.06, "fall": 0.16, "dive": 0.07, "dive_land": 0.06, "splash": 0.08, "recover": 0.12,
	"stumble": 0.06, "flop": 0.1, "dizzy": 0.3, "tag_windup": 0.05, "tag_lunge": 0.04, "tag_recover": 0.08,
	"cart_enter": 0.08, "cart": 0.12, "cart_exit": 0.06, "celebrate": 0.15, "arrive": 0.05,
	"emote_wave": 0.15, "emote_cheer": 0.15, "emote_laugh": 0.15, "emote_shrug": 0.15, "emote_dance": 0.15, "emote_point": 0.15,
}
const UPPER_BODY := ["spine", "chest", "neck", "head", "shoulder.L", "shoulder.R", "upper_arm.L", "upper_arm.R",
	"forearm.L", "forearm.R", "hand.L", "hand.R"]

static var _material: ShaderMaterial

var role: int = TC.Role.RUNNER
var cosmetic: Dictionary = Cosmetics.DEFAULT
var slot: int = -1
var is_local := false
var reduced_motion := false
var rs: Dictionary = {}
## "outdoor" (cool moon rim) or "indoor" (warm lamp rim); set before setup()
var lighting := "outdoor"

var model: Node3D
var skeleton: Skeleton3D
var anim: AnimationPlayer
var tree: AnimationTree
var secondary: CharacterSecondary
var hat_spring: SpringBoneSimulator3D
var parts: Dictionary = {}          # name -> MeshInstance3D
var visible_parts: Array[MeshInstance3D] = []
var base_mesh: MeshInstance3D
var name_label: Label3D
var flashlight: SpotLight3D
var beam: MeshInstance3D
var dizzy: Node3D
var bubble: MeshInstance3D

var _mode := ""
var _mode_t := 0.0
var _prev_state := -1
var _prev_air := false
var _prev_diving := false
var _prev_vel := Vector3.ZERO
var _prev_yaw := 0.0
var _have_prev := false
var _fall_speed := 0.0
var _dive_land_t := 0.0
var _recover_t := 0.0
var _arrive_t := 0.0
var _turn_cd := 0.0
var _yaw_accum := 0.0
var _phase := 0.0
var _blink_t := 2.0
var _blink := 0.0
var _rng := RandomNumberGenerator.new()
var _face := {"blink": 0.0, "squint": 0.0, "smile": 0.0, "open": 0.0, "brow_up": 0.0, "brow_angry": 0.0}
var _face_idx := {}
var _squash := 0.0
var _t := 0.0
var _anim_skip := 0
var _upper_filter: Array[NodePath] = []


static func _shared_material() -> ShaderMaterial:
	if _material == null:
		_material = ShaderMaterial.new()
		_material.shader = SHADER
	return _material


func setup(p_role: int, p_cosmetic: Dictionary, p_slot: int, display_name: String, is_bot: bool, local: bool = false) -> void:
	role = p_role
	cosmetic = Cosmetics.sanitize(p_cosmetic)
	slot = p_slot
	is_local = local
	_rng.seed = hash(p_slot * 7919 + 17)
	if model == null:
		_build_model()
	_apply_cosmetics()
	_build_label(display_name, is_bot)


## Change outfit/role in place (no rebuild; used by lobby and wardrobe).
func set_appearance(p_role: int, p_cosmetic: Dictionary) -> void:
	role = p_role
	cosmetic = Cosmetics.sanitize(p_cosmetic)
	if model != null:
		_apply_cosmetics()
		if name_label:
			name_label.modulate = _label_color()


func _build_model() -> void:
	model = SCENE.instantiate()
	add_child(model)
	skeleton = model.find_children("*", "Skeleton3D", true, false)[0]
	anim = model.find_children("*", "AnimationPlayer", true, false)[0]
	for c in skeleton.get_children():
		if c is MeshInstance3D:
			var mi := c as MeshInstance3D
			parts[String(mi.name)] = mi
			mi.material_override = _shared_material()
			mi.visible = false
	base_mesh = parts.get("base")
	for i in base_mesh.mesh.get_blend_shape_count():
		_face_idx[String(base_mesh.mesh.get_blend_shape_name(i))] = i
	_prepare_animations()
	_build_tree()
	secondary = CharacterSecondary.new()
	skeleton.add_child(secondary)
	_build_effects()


func _prepare_animations() -> void:
	# loop flags come from the asset manifest; the library resource is shared
	# by every instance, so this runs once per resource
	var lib := anim.get_animation_library("")
	if lib == null or lib.has_meta("ut_prepared"):
		return
	for n in lib.get_animation_list():
		var a := lib.get_animation(n)
		var looped := String(n) in ["idle", "walk", "run", "sprint", "fall", "dizzy", "cart_drive", "cart_steer_l",
			"cart_steer_r", "celebrate"] or String(n).begins_with("emote_")
		a.loop_mode = Animation.LOOP_LINEAR if looped else Animation.LOOP_NONE
	lib.set_meta("ut_prepared", true)


func _anim_node(n: String) -> AnimationNodeAnimation:
	var a := AnimationNodeAnimation.new()
	a.animation = n
	return a


func _build_tree() -> void:
	var bt := AnimationNodeBlendTree.new()
	bt.add_node("idle", _anim_node("idle"))
	var loco := AnimationNodeBlendSpace1D.new()
	loco.min_space = 0.0
	loco.max_space = 9.0
	loco.sync = true
	for k in LOCO_POINTS:
		loco.add_blend_point(_anim_node(k), LOCO_POINTS[k], -1, k)
	bt.add_node("loco", loco)
	bt.add_node("loco_rate", AnimationNodeTimeScale.new())
	bt.connect_node("loco_rate", 0, "loco")
	var move := AnimationNodeBlend2.new()
	move.sync = true
	bt.add_node("move", move)
	bt.connect_node("move", 0, "idle")
	bt.connect_node("move", 1, "loco_rate")
	var tdir := AnimationNodeTransition.new()
	tdir.add_input("l")
	tdir.add_input("r")
	tdir.xfade_time = 0.0
	bt.add_node("turn_dir", tdir)
	bt.add_node("turn_l", _anim_node("turn_l"))
	bt.add_node("turn_r", _anim_node("turn_r"))
	bt.connect_node("turn_dir", 0, "turn_l")
	bt.connect_node("turn_dir", 1, "turn_r")
	var turn := AnimationNodeOneShot.new()
	turn.fadein_time = 0.08
	turn.fadeout_time = 0.12
	bt.add_node("turn", turn)
	bt.connect_node("turn", 0, "move")
	bt.connect_node("turn", 1, "turn_dir")
	var cart := AnimationNodeBlendSpace1D.new()
	cart.min_space = -1.0
	cart.max_space = 1.0
	cart.sync = true
	cart.add_blend_point(_anim_node("cart_steer_r"), -1.0, -1, "steer_r")
	cart.add_blend_point(_anim_node("cart_drive"), 0.0, -1, "drive")
	cart.add_blend_point(_anim_node("cart_steer_l"), 1.0, -1, "steer_l")
	bt.add_node("cart_bs", cart)
	var st := AnimationNodeTransition.new()
	st.xfade_time = 0.12
	var i := 0
	for s in STATES:
		st.add_input(s)
		st.set_input_reset(i, true)
		i += 1
		if s == "ground":
			continue
		if s == "cart":
			continue
		bt.add_node("a_" + s, _anim_node("dizzy" if s == "dizzy" else s))
	bt.add_node("state", st)
	i = 0
	for s in STATES:
		if s == "ground":
			bt.connect_node("state", i, "turn")
		elif s == "cart":
			bt.connect_node("state", i, "cart_bs")
		else:
			bt.connect_node("state", i, "a_" + s)
		i += 1
	var land := AnimationNodeOneShot.new()
	land.fadein_time = 0.03
	land.fadeout_time = 0.14
	land.filter_enabled = true
	var root_path := String(anim.get_parent().get_path_to(skeleton)) if anim.get_parent() else "Runner/Skeleton3D"
	for b in UPPER_BODY:
		land.set_filter_path(NodePath(root_path + ":" + b), true)
	bt.add_node("a_land", _anim_node("land"))
	bt.add_node("land", land)
	bt.connect_node("land", 0, "state")
	bt.connect_node("land", 1, "a_land")
	bt.connect_node("output", 0, "land")
	tree = AnimationTree.new()
	tree.name = "AnimTree"
	tree.tree_root = bt
	model.add_child(tree)
	tree.anim_player = tree.get_path_to(anim)
	tree.root_node = tree.get_path_to(anim.get_node(anim.root_node))
	tree.callback_mode_process = AnimationMixer.ANIMATION_CALLBACK_MODE_PROCESS_MANUAL
	tree.active = true
	_mode = ""
	_set_mode("ground")


func _build_effects() -> void:
	PropKit.init_meshes()
	dizzy = Node3D.new()
	dizzy.position = Vector3(0, 1.75, 0)
	add_child(dizzy)
	for k in 3:
		var a := TAU * float(k) / 3.0
		var s := MeshInstance3D.new()
		s.mesh = PropKit.sphere
		s.material_override = PropKit.mat(Color(1.0, 0.86, 0.35), 0.0, Color.WHITE, 1.2)
		s.position = Vector3(cos(a) * 0.32, 0, sin(a) * 0.32)
		s.scale = Vector3.ONE * 0.09
		s.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		dizzy.add_child(s)
	dizzy.visible = false
	bubble = MeshInstance3D.new()
	bubble.mesh = PropKit.sphere
	var bmat := StandardMaterial3D.new()
	bmat.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	bmat.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	bmat.albedo_color = Color(0.44, 0.85, 0.8, 0.14)
	bmat.cull_mode = BaseMaterial3D.CULL_BACK
	bubble.material_override = bmat
	bubble.scale = Vector3(1.4, 1.9, 1.4)
	bubble.position = Vector3(0, 0.85, 0)
	bubble.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	bubble.visible = false
	add_child(bubble)


func _build_flashlight() -> void:
	if flashlight != null:
		return
	var hand := skeleton.find_bone("hand.R")
	var att := BoneAttachment3D.new()
	att.bone_name = "hand.R"
	skeleton.add_child(att)
	# the flashlight mesh is built pointing along the model's forward (-Z)
	# at rest; keep the light aligned with it relative to the hand bone
	var lens_rest := Transform3D(Basis(), Vector3(0.409, 0.555, -0.105))
	var bone_rest := skeleton.get_bone_global_rest(hand)
	var holder := Node3D.new()
	holder.transform = bone_rest.affine_inverse() * lens_rest
	att.add_child(holder)
	flashlight = SpotLight3D.new()
	flashlight.light_color = Color(1.0, 0.95, 0.82)
	flashlight.light_energy = 2.6
	flashlight.spot_range = 20.0
	flashlight.spot_angle = 22.0
	flashlight.spot_attenuation = 0.9
	flashlight.shadow_enabled = false
	holder.add_child(flashlight)
	beam = MeshInstance3D.new()
	var bm := CylinderMesh.new()
	bm.top_radius = 0.05
	bm.bottom_radius = 2.4
	bm.height = 9.0
	bm.radial_segments = 16
	bm.cap_top = false
	bm.cap_bottom = false
	beam.mesh = bm
	var gm := ShaderMaterial.new()
	gm.shader = preload("res://assets/shaders/glow_add.gdshader")
	gm.set_shader_parameter("color", Color(1.0, 0.92, 0.72))
	gm.set_shader_parameter("intensity", 0.1)
	gm.set_shader_parameter("mode", 2.0)
	beam.material_override = gm
	beam.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	# CylinderMesh top (UV.y = 0, brightest in glow_add) sits at the lens
	beam.position = Vector3(0, 0, -4.6)
	beam.rotation = Vector3(PI * 0.5, 0, 0)
	holder.add_child(beam)


func _label_color() -> Color:
	return Color("ffc668") if role == TC.Role.PATROL else Color("f4f2ec")


func _build_label(display_name: String, is_bot: bool) -> void:
	if name_label == null:
		name_label = Label3D.new()
		add_child(name_label)
	name_label.text = (display_name + "  ·  BOT") if is_bot else display_name
	name_label.font = UIKit.font(true)
	name_label.font_size = 30
	name_label.outline_size = 10
	name_label.pixel_size = 0.0011
	name_label.billboard = BaseMaterial3D.BILLBOARD_ENABLED
	name_label.no_depth_test = false
	name_label.fixed_size = true
	name_label.position = Vector3(0, 2.05, 0)
	name_label.modulate = _label_color()
	name_label.outline_modulate = Color("11192b")
	name_label.visibility_range_end = 30.0
	name_label.visibility_range_end_margin = 8.0
	name_label.visibility_range_fade_mode = GeometryInstance3D.VISIBILITY_RANGE_FADE_SELF
	name_label.visible = not is_local and display_name != ""


func _apply_cosmetics() -> void:
	var want: Array[String] = ["base"]
	var outfit: String = cosmetic["outfit"]
	var hat: String = cosmetic["hat"]
	var patrol := role == TC.Role.PATROL
	if patrol:
		want.append_array(["watch", "flashlight"])
		if int(cosmetic["color"]) % 2 == 0:
			want.append("mustache")
	else:
		for p in OUTFIT_PARTS.get(outfit, ["pj"]):
			want.append(p)
		var hood := outfit in HOOD_OUTFITS
		if not hood:
			for p in HAT_PARTS.get(hat, []):
				want.append(p)
			if not hat in HATS_HIDING_HAIR:
				want.append("hair")
		for p in SHOE_PARTS.get(String(cosmetic["shoes"]), ["shoe_slippers"]):
			want.append(p)
	visible_parts.clear()
	for n in parts:
		var mi: MeshInstance3D = parts[n]
		mi.visible = n in want
		if mi.visible:
			visible_parts.append(mi)
	var prim: Color = Cosmetics.COLORS[int(cosmetic["color"])]
	var sec := prim.lerp(Color.WHITE, 0.55) if prim.get_luminance() < 0.72 else prim.darkened(0.28)
	var dark := prim.darkened(0.38)
	var skin: Color = Cosmetics.SKINS[int(cosmetic["skin"])]
	var hair: Color = HAIR_BY_SKIN[int(cosmetic["skin"]) % HAIR_BY_SKIN.size()]
	var stripes := STRIPES_PER_M if (not patrol and outfit == "pj_stripes") else 0.0
	var rim := Color(1.0, 0.78, 0.55) if lighting == "indoor" else Color(0.55, 0.68, 1.0)
	for mi in visible_parts:
		mi.set_instance_shader_parameter("tint_primary", prim)
		mi.set_instance_shader_parameter("tint_secondary", sec)
		mi.set_instance_shader_parameter("tint_dark", dark)
		mi.set_instance_shader_parameter("tint_skin", skin)
		mi.set_instance_shader_parameter("tint_hair", hair)
		mi.set_instance_shader_parameter("stripes", stripes)
		mi.set_instance_shader_parameter("rim_color", rim)
		mi.set_instance_shader_parameter("rim_strength", 0.14 if lighting == "indoor" else 0.1)
	# nightcap tip spring only when it is worn
	var cap := not patrol and hat == "nightcap" and not outfit in HOOD_OUTFITS
	if cap and hat_spring == null:
		hat_spring = SpringBoneSimulator3D.new()
		skeleton.add_child(hat_spring)
		hat_spring.setting_count = 1
		hat_spring.set_root_bone_name(0, "hat1")
		hat_spring.set_end_bone_name(0, "hat3")
		hat_spring.set_extend_end_bone(0, true)
		hat_spring.set_end_bone_length(0, 0.1)
		hat_spring.set_stiffness(0, 1.6)
		hat_spring.set_drag(0, 0.45)
		hat_spring.set_gravity(0, 0.4)
		hat_spring.set_radius(0, 0.03)
	if hat_spring:
		hat_spring.active = cap
	if patrol:
		_build_flashlight()
	if flashlight:
		flashlight.get_parent().visible = patrol


func set_flash(v: float, col: Color = Color.WHITE) -> void:
	for mi in visible_parts:
		mi.set_instance_shader_parameter("flash", v)
		mi.set_instance_shader_parameter("flash_color", col)


## Turn to look at a point (menus/lobby): yaw such that -Z points at `p`.
func face_toward(p: Vector3) -> void:
	var d := p - global_position
	rotation.y = atan2(-d.x, -d.z)


## One brief arrival hop (lobby).
func play_arrive() -> void:
	_arrive_t = 0.9


## Hard reset of presentation history (respawn, teleport, cart entry/exit,
## reconnect, spectator switch): no lag/spring carries across the jump.
func reset_motion() -> void:
	_have_prev = false
	_prev_vel = Vector3.ZERO
	_squash = 0.0
	if secondary:
		secondary.reset_motion()
	if hat_spring:
		hat_spring.reset()


## rs keys: pos, yaw, vel, state, state_t, on_floor, diving, sprinting,
## tag_phase, protect, bump_protect, spotted, cart_id, steer, emote, emote_t,
## celebrate, show_finished, visible.  The caller supplies render-time values
## (already interpolated); this view does not smooth position again.
func apply_state(state_rs: Dictionary, _delta: float = 0.0, snap: bool = false) -> void:
	rs = state_rs
	if rs.has("pos"):
		global_position = rs["pos"]
	if rs.has("yaw"):
		rotation.y = float(rs["yaw"])
	if snap:
		reset_motion()


func _set_mode(m: String) -> void:
	if m == _mode or tree == null:
		return
	var st := tree.tree_root.get_node("state") as AnimationNodeTransition
	st.xfade_time = STATES.get(m, 0.12) * (0.5 if reduced_motion else 1.0)
	tree.set("parameters/state/transition_request", m)
	_mode = m
	_mode_t = 0.0


func _process(delta: float) -> void:
	if model == null or rs.is_empty():
		return
	_t += delta
	_mode_t += delta
	var st: int = rs.get("state", TC.PState.ACTIVE)
	var vel: Vector3 = rs.get("vel", Vector3.ZERO)
	var speed := Vector2(vel.x, vel.z).length()
	var on_floor: bool = rs.get("on_floor", true)
	var diving: bool = rs.get("diving", false)
	var sprinting: bool = rs.get("sprinting", false)
	var tag_phase: int = rs.get("tag_phase", 0)
	var state_t: float = rs.get("state_t", 0.0)
	var finished := st == TC.PState.FINISHED
	var captured := st == TC.PState.CAPTURED
	var emote: int = rs.get("emote", -1)
	var emote_t: float = rs.get("emote_t", 0.0)
	visible = not finished or bool(rs.get("show_finished", false))

	# --- motion history (acceleration from the previous frame's velocity)
	var yaw := rotation.y
	var accel := Vector3.ZERO
	var yaw_rate := 0.0
	if _have_prev and delta > 0.0:
		accel = (vel - _prev_vel) / delta
		yaw_rate = wrapf(yaw - _prev_yaw, -PI, PI) / delta
	if st != _prev_state and _prev_state >= 0:
		# discontinuities: respawn after capture, splash resurfacing, cart in/out
		if _prev_state in [TC.PState.CAPTURED, TC.PState.SPLASHING, TC.PState.IN_CART, TC.PState.EXITING] or st == TC.PState.ENTERING:
			reset_motion()
			accel = Vector3.ZERO
			yaw_rate = 0.0
		if _prev_state == TC.PState.SPLASHING and st == TC.PState.ACTIVE:
			_recover_t = 0.6
	_prev_vel = vel
	_prev_yaw = yaw
	_have_prev = true
	_prev_state = st
	if secondary:
		secondary.accel = global_transform.basis.inverse() * accel
		secondary.turn_rate = yaw_rate
		secondary.speed = speed
		secondary.gain = 0.4 if reduced_motion else 1.0

	# --- landing / jump / dive edges (sounds + squash), once per edge
	var air := not on_floor
	if air:
		_fall_speed = maxf(_fall_speed, -vel.y)
	if _prev_air and not air and st == TC.PState.ACTIVE:
		if _prev_diving or diving:
			_dive_land_t = 0.32
		elif _fall_speed > 3.0:
			tree.set("parameters/land/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)
			_squash = clampf(_fall_speed * 0.02, 0.06, 0.18)
			if _near_camera(25.0):
				Sfx.play("land", global_position, -4.0)
		_fall_speed = 0.0
	if not _prev_air and air and vel.y > 2.0 and st == TC.PState.ACTIVE:
		_squash = -0.08
		if _near_camera(25.0):
			Sfx.play("jump", global_position, -6.0)
	if diving and not _prev_diving and _near_camera(25.0):
		Sfx.play("dive", global_position, -4.0)
	_prev_air = air
	_prev_diving = diving
	_dive_land_t = maxf(0.0, _dive_land_t - delta)
	_recover_t = maxf(0.0, _recover_t - delta)
	_arrive_t = maxf(0.0, _arrive_t - delta)
	_turn_cd = maxf(0.0, _turn_cd - delta)

	# --- choose the animation state
	var m := "ground"
	if st == TC.PState.ENTERING:
		m = "cart_enter"
	elif st == TC.PState.IN_CART:
		m = "cart"
	elif st == TC.PState.EXITING:
		m = "cart_exit"
	elif captured:
		m = "flop" if state_t < 0.9 else "dizzy"
	elif st == TC.PState.SPLASHING:
		m = "splash"
	elif st == TC.PState.STUMBLE:
		m = "stumble"
	elif finished or bool(rs.get("celebrate", false)):
		m = "celebrate"
	elif diving:
		m = "dive"
	elif _dive_land_t > 0.0:
		m = "dive_land"
	elif tag_phase == 1:
		m = "tag_windup"
	elif tag_phase == 2:
		m = "tag_lunge"
	elif tag_phase == 3:
		m = "tag_recover"
	elif air:
		m = "jump" if vel.y > 0.0 else "fall"
		if _mode == "jump" and _mode_t < 0.2 and vel.y > -2.0:
			m = "jump"
	elif _recover_t > 0.0:
		m = "recover"
	elif emote >= 0 and emote_t > 0.0 and speed < 1.0:
		m = "emote_" + TC.EMOTES[emote]
	elif _arrive_t > 0.0:
		m = "arrive"
	_set_mode(m)

	# --- locomotion parameters (speed-matched playback: no foot sliding)
	if m == "ground":
		var bs := clampf(speed, LOCO_POINTS["walk"], LOCO_POINTS["sprint"])
		tree.set("parameters/loco/blend_position", bs)
		tree.set("parameters/loco_rate/scale", speed / _m_per_cycle(bs) if speed > 0.05 else 0.0)
		tree.set("parameters/move/blend_amount", smoothstep(0.15, 0.9, speed))
		_phase += delta * (speed / _m_per_cycle(bs))
		# footsteps at mid-stance of each foot (0 and 0.5 of the cycle)
		if on_floor and speed > 3.2 and int(floor((_phase - delta * (speed / _m_per_cycle(bs))) * 2.0)) != int(floor(_phase * 2.0)) and _near_camera(30.0):
			Sfx.play("step", global_position, -6.0 + (4.0 if sprinting else 0.0) + (2.0 if role == TC.Role.PATROL else 0.0), 0.9 if role == TC.Role.PATROL else 1.1)
		# turn in place
		if speed < 0.4:
			_yaw_accum += yaw_rate * delta
			_yaw_accum *= exp(-delta * 4.0)
			if absf(_yaw_accum) > 0.5 and _turn_cd <= 0.0:
				tree.set("parameters/turn_dir/transition_request", "l" if _yaw_accum > 0.0 else "r")
				tree.set("parameters/turn/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)
				_turn_cd = 0.45
				_yaw_accum = 0.0
		else:
			_yaw_accum = 0.0
	elif m == "cart":
		tree.set("parameters/cart_bs/blend_position", clampf(float(rs.get("steer", 0.0)), -1.0, 1.0))

	# --- squash & stretch (scale about the feet), small and fast
	_squash = move_toward(_squash, 0.0, delta * 1.2)
	var sq := _squash * (0.4 if reduced_motion else 1.0)
	model.scale = Vector3(1.0 + sq * 0.5, 1.0 - sq, 1.0 + sq * 0.5)

	# --- effects
	dizzy.visible = captured and state_t > 0.5 and state_t < 4.5
	if dizzy.visible:
		dizzy.rotation.y += delta * 5.0
	bubble.visible = float(rs.get("protect", 0.0)) > 0.0 and not captured
	if bubble.visible:
		(bubble.material_override as StandardMaterial3D).albedo_color.a = 0.10 + 0.06 * sin(_t * 10.0)
	if flashlight:
		var show_light := role == TC.Role.PATROL and m != "cart" and m != "cart_enter"
		flashlight.visible = show_light
		beam.visible = show_light
	var flash := 0.0
	if float(rs.get("protect", 0.0)) > 0.0:
		flash = 0.18 + 0.14 * sin(_t * 16.0)
	elif float(rs.get("bump_protect", 0.0)) > 0.0:
		flash = 0.15
	set_flash(flash, Color("6fd8cc"))

	# --- face
	_update_face(delta, m, sprinting, tag_phase, bool(rs.get("spotted", false)))

	# --- animate (manual advance: distant characters update at a lower rate)
	if not tree.active:
		return
	var far := not is_local and not _near_camera(45.0)
	_anim_skip += 1
	if not far or _anim_skip >= 3:
		tree.advance(delta * (float(_anim_skip) if far else 1.0))
		_anim_skip = 0


func _m_per_cycle(bs: float) -> float:
	if bs <= LOCO_POINTS["run"]:
		return lerpf(LOCO_M_PER_CYCLE["walk"], LOCO_M_PER_CYCLE["run"], inverse_lerp(LOCO_POINTS["walk"], LOCO_POINTS["run"], bs))
	return lerpf(LOCO_M_PER_CYCLE["run"], LOCO_M_PER_CYCLE["sprint"], inverse_lerp(LOCO_POINTS["run"], LOCO_POINTS["sprint"], bs))


func _update_face(delta: float, m: String, sprinting: bool, tag_phase: int, spotted: bool) -> void:
	var tgt := {"blink": 0.0, "squint": 0.0, "smile": 0.0, "open": 0.0, "brow_up": 0.0, "brow_angry": 0.0}
	match m:
		"celebrate", "emote_cheer", "emote_laugh", "emote_dance", "arrive":
			tgt["squint"] = 1.0
			tgt["smile"] = 1.0
			tgt["open"] = 0.55
		"splash", "fall", "stumble", "flop":
			tgt["open"] = 0.85
			tgt["brow_up"] = 1.0
		"dizzy":
			tgt["squint"] = 0.6
			tgt["open"] = 0.3
			tgt["brow_up"] = 0.5
		"tag_windup", "tag_lunge", "dive":
			tgt["brow_angry"] = 1.0
			tgt["open"] = 0.35
		"emote_wave", "emote_point":
			tgt["smile"] = 0.9
			tgt["open"] = 0.3
		"emote_shrug":
			tgt["brow_up"] = 0.8
		"recover":
			tgt["squint"] = 0.8
			tgt["open"] = 0.3
		_:
			tgt["smile"] = 0.35
			if sprinting or tag_phase > 0:
				tgt["brow_angry"] = 0.8
				tgt["smile"] = 0.0
	if spotted:
		tgt["brow_up"] = 1.0
		tgt["open"] = maxf(float(tgt["open"]), 0.6)
		tgt["smile"] = 0.0
	# blinking (never while squinting)
	_blink_t -= delta
	if _blink_t <= 0.0:
		_blink_t = _rng.randf_range(2.2, 4.6)
		_blink = 0.13
	_blink = maxf(0.0, _blink - delta)
	if _blink > 0.0 and float(tgt["squint"]) < 0.5:
		tgt["blink"] = 1.0
	var k := 1.0 - exp(-delta * 18.0)
	for key in _face:
		var target: float = tgt[key]
		_face[key] = target if key == "blink" else lerpf(float(_face[key]), target, k)
		if _face_idx.has(key):
			base_mesh.set_blend_shape_value(_face_idx[key], float(_face[key]))


func _near_camera(r: float) -> bool:
	var cam := get_viewport().get_camera_3d() if is_inside_tree() else null
	return cam != null and cam.global_position.distance_to(global_position) < r
