class_name CharacterView
extends Node3D
## The skinned Trifecta runner / Night Watch character (one shared asset:
## assets/characters/runner.glb, generated by tools/character/build_character.py).
## Used identically by gameplay, lobby, creator, home and results.
##
## Presentation only: it shows authoritative/interpolated state and never
## moves gameplay (the gameplay capsule lives in the sim).  Nothing here
## changes speed, reach, immunity, objective credit or action timing.
##
## Forward convention: at yaw 0 the character faces -Z, the same as the sim's
## yaw (forward = Basis(UP, yaw) * -Z) and Godot cameras.  Use face_toward()
## to turn a character to the camera in menu scenes.
##
## Animation graph (built per instance, advanced manually at the end of
## _process so the state chosen this frame is the pose drawn this frame):
##   ground  = idle (seeked, per-instance offset) <-> locomotion blend space
##             (walk/run/sprint, seeked to this view's gait phase) + a
##             turn-in-place one-shot
##   air     = blend space over vertical velocity (rise / apex / fall), so the
##             top of a jump never pops
##   splash  = one of three impact clips seeked to the runner's authoritative
##             time in the water (a late joiner sees the right beat)
##   others  = Transition states (dive, tag, cart, celebrate, emotes, ...)
##   overlays: full-body and upper-body landing one-shots (soft/hard mix),
##             an upper-body recovery shake-off (legs keep running) and idle
##             fidgets.
## CharacterSecondary adds head lag and banking; a spring-bone chain moves
## the nightcap tip.  Face shapes are blend shapes on "base".

const SCENE := preload("res://assets/characters/runner.glb")
const SHADER := preload("res://assets/shaders/character.gdshader")

## m/s at which each locomotion clip is blended in (blend-space positions)
const LOCO_POINTS := {"walk": 1.3, "run": 5.0, "sprint": 7.0}
## metres per 1.0 s cycle at rate 1 and stance fraction (runner_manifest.json,
## tools/character/anims.py LOCO).  gait rate = speed / metres-per-cycle.
const LOCO_M_PER_CYCLE := {"walk": 0.70, "run": 2.20, "sprint": 2.75}
const LOCO_DUTY := {"walk": 0.58, "run": 0.20, "sprint": 0.165}
const IDLE_LEN := 4.0
const SPLASH_LEN := 1.5
## air blend space positions (vertical m/s)
const AIR_POINTS := {"air_fall": -7.0, "air_apex": 0.0, "air_rise": 5.5}
## impact class carried by the splash (sim: SimPlayer.splash_impact)
const IMPACTS := ["splash_walk", "splash_jump", "splash_dive"]

const HAIR_BY_SKIN := [Color("4a3222"), Color("2e1e15"), Color("1f1712"), Color("151010"), Color("b8743f")]

## state name -> xfade seconds into that state
const STATES := {
	"ground": 0.16, "air": 0.1, "dive": 0.07, "dive_land": 0.06, "splash": 0.06,
	"stumble": 0.06, "flop": 0.1, "dizzy": 0.3, "tag_windup": 0.05, "tag_lunge": 0.04, "tag_recover": 0.08, "tag_miss": 0.08,
	"cart_enter": 0.08, "cart": 0.12, "cart_exit": 0.06, "celebrate": 0.15, "arrive": 0.05, "ready": 0.08,
	"emote_wave": 0.15, "emote_cheer": 0.15, "emote_laugh": 0.15, "emote_shrug": 0.15, "emote_dance": 0.15, "emote_point": 0.15,
}
const UPPER_BODY := ["spine", "chest", "neck", "head", "shoulder.L", "shoulder.R", "upper_arm.L", "upper_arm.R",
	"forearm.L", "forearm.R", "hand.L", "hand.R"]
const FIDGETS := ["fidget_yawn", "fidget_look"]
const EXPRESSIONS := ["blink", "squint", "smile", "open", "brow_up", "brow_angry"]

static var _material: ShaderMaterial

var role: int = TC.Role.RUNNER
var cosmetic: Dictionary = Cosmetics.DEFAULT
var slot: int = -1
var is_local := false
var reduced_motion := false
## idle fidgets (yawn, look around) after standing still for a while
var fidgets := true
var rs: Dictionary = {}
## "outdoor" (cool moon rim) or "indoor" (warm lamp rim); set before setup()
var lighting := "outdoor"
## optional: the match's Fx node and a water lookup (pos -> {mat, center,
## color}) for splash beats; left empty in menus
var fx: Fx
var water_at: Callable

var model: Node3D
var skeleton: Skeleton3D
var anim: AnimationPlayer
var tree: AnimationTree
var secondary: CharacterSecondary
var hat_spring: SpringBoneSimulator3D
var parts: Dictionary = {}          # name -> MeshInstance3D
var visible_parts: Array[MeshInstance3D] = []
var base_mesh: MeshInstance3D
var name_label: Label3D
var flashlight: SpotLight3D
var beam: MeshInstance3D
var dizzy: Node3D
var bubble: MeshInstance3D
var drips: CPUParticles3D

var _mode := ""
var _mode_t := 0.0
var _prev_state := -1
var _prev_air := false
var _prev_diving := false
var _prev_vel := Vector3.ZERO
var _prev_yaw := 0.0
var _have_prev := false
var _vis_yaw := 0.0
var _have_yaw := false
var _turn_sign := 0.0
var _fall_speed := 0.0
var _air_t := 0.0
var _since_land := 9.0
var _since_jump := 9.0
var _dive_land_t := 0.0
var _arrive_t := 0.0
var _ready_t := 0.0
var _miss_t := 0.0
var _turn_cd := 0.0
var _yaw_accum := 0.0
var _phase := 0.0
var _step_k := 0
var _step_init := false
var _idle_off := 0.0
var _still_t := 0.0
var _next_fidget := 8.0
var _fidget_on := false
var _splash_t := -1.0
var _splash_kind := 0
var _splash_beats := 0
var _splash_pos := Vector3.ZERO
var _wet := 0.0
var _drip_t := 0.0
var _blink_t := 2.0
var _blink := 0.0
var _rng := RandomNumberGenerator.new()
var _face := {}
var _face_base := {}
var _face_idx := {}
var _squash := 0.0
var _t := 0.0
var _anim_skip := 0
var _anim_acc := 0.0
## total animation time advanced (tests: equals the real elapsed time)
var anim_time_advanced := 0.0


static func _shared_material() -> ShaderMaterial:
	if _material == null:
		_material = ShaderMaterial.new()
		_material.shader = SHADER
	return _material


func setup(p_role: int, p_cosmetic: Dictionary, p_slot: int, display_name: String, is_bot: bool, local: bool = false) -> void:
	role = p_role
	cosmetic = Cosmetics.sanitize(p_cosmetic)
	slot = p_slot
	is_local = local
	_rng.seed = hash(str(p_slot) + display_name + str(get_instance_id()))
	_idle_off = _rng.randf() * IDLE_LEN
	_phase = _rng.randf()
	_next_fidget = _rng.randf_range(6.0, 14.0)
	_blink_t = _rng.randf_range(0.5, 3.0)
	if model == null:
		_build_model()
	_apply_cosmetics()
	_build_label(display_name, is_bot)


## Change outfit/role in place (no rebuild; used by lobby and creator).
func set_appearance(p_role: int, p_cosmetic: Dictionary) -> void:
	role = p_role
	cosmetic = Cosmetics.sanitize(p_cosmetic)
	if model != null:
		_apply_cosmetics()
		if name_label:
			name_label.modulate = _label_color()


func _build_model() -> void:
	model = SCENE.instantiate()
	add_child(model)
	skeleton = model.find_children("*", "Skeleton3D", true, false)[0]
	anim = model.find_children("*", "AnimationPlayer", true, false)[0]
	for c in skeleton.get_children():
		if c is MeshInstance3D:
			var mi := c as MeshInstance3D
			parts[String(mi.name)] = mi
			mi.material_override = _shared_material()
			mi.visible = false
	base_mesh = parts.get("base")
	for i in base_mesh.mesh.get_blend_shape_count():
		_face_idx[String(base_mesh.mesh.get_blend_shape_name(i))] = i
	for k in _face_idx:
		_face[k] = 0.0
	_prepare_animations()
	_build_tree()
	secondary = CharacterSecondary.new()
	skeleton.add_child(secondary)
	_build_effects()


func _prepare_animations() -> void:
	# loop flags come from the asset manifest; the library resource is shared
	# by every instance, so this runs once per resource
	var lib := anim.get_animation_library("")
	if lib == null or lib.has_meta("ut_prepared"):
		return
	for n in lib.get_animation_list():
		var a := lib.get_animation(n)
		var looped := String(n) in ["idle", "walk", "run", "sprint", "air_rise", "air_apex", "air_fall", "dizzy",
			"cart_drive", "cart_steer_l", "cart_steer_r", "celebrate"] or String(n).begins_with("emote_")
		a.loop_mode = Animation.LOOP_LINEAR if looped else Animation.LOOP_NONE
	lib.set_meta("ut_prepared", true)


func _anim_node(n: String) -> AnimationNodeAnimation:
	var a := AnimationNodeAnimation.new()
	a.animation = n
	return a


func _seek_node() -> AnimationNodeTimeSeek:
	var s := AnimationNodeTimeSeek.new()
	s.explicit_elapse = false
	return s


func _filtered(n: AnimationNodeOneShot) -> void:
	n.filter_enabled = true
	var root_path := String(anim.get_parent().get_path_to(skeleton)) if anim.get_parent() else "Runner/Skeleton3D"
	for b in UPPER_BODY:
		n.set_filter_path(NodePath(root_path + ":" + b), true)


func _build_tree() -> void:
	var bt := AnimationNodeBlendTree.new()
	# --- ground: idle (seeked) <-> loco (seeked to the gait phase)
	bt.add_node("a_idle", _anim_node("idle"))
	bt.add_node("idle_seek", _seek_node())
	bt.connect_node("idle_seek", 0, "a_idle")
	var loco := AnimationNodeBlendSpace1D.new()
	loco.min_space = 0.0
	loco.max_space = 9.0
	loco.sync = true
	for k in LOCO_POINTS:
		loco.add_blend_point(_anim_node(k), LOCO_POINTS[k], -1, k)
	bt.add_node("loco", loco)
	bt.add_node("loco_seek", _seek_node())
	bt.connect_node("loco_seek", 0, "loco")
	var move := AnimationNodeBlend2.new()
	bt.add_node("move", move)
	bt.connect_node("move", 0, "idle_seek")
	bt.connect_node("move", 1, "loco_seek")
	var tdir := AnimationNodeTransition.new()
	tdir.add_input("l")
	tdir.add_input("r")
	tdir.xfade_time = 0.0
	bt.add_node("turn_dir", tdir)
	bt.add_node("turn_l", _anim_node("turn_l"))
	bt.add_node("turn_r", _anim_node("turn_r"))
	bt.connect_node("turn_dir", 0, "turn_l")
	bt.connect_node("turn_dir", 1, "turn_r")
	var turn := AnimationNodeOneShot.new()
	turn.fadein_time = 0.08
	turn.fadeout_time = 0.12
	bt.add_node("turn", turn)
	bt.connect_node("turn", 0, "move")
	bt.connect_node("turn", 1, "turn_dir")
	# --- air: vertical-velocity blend space
	var air := AnimationNodeBlendSpace1D.new()
	air.min_space = -9.0
	air.max_space = 9.0
	for k in AIR_POINTS:
		air.add_blend_point(_anim_node(k), AIR_POINTS[k], -1, k)
	bt.add_node("air", air)
	# --- splash: impact clip seeked to the authoritative time in the water
	var sk := AnimationNodeTransition.new()
	sk.xfade_time = 0.0
	for i in IMPACTS.size():
		sk.add_input(str(i))
		bt.add_node("a_" + IMPACTS[i], _anim_node(IMPACTS[i]))
	bt.add_node("splash_kind", sk)
	for i in IMPACTS.size():
		bt.connect_node("splash_kind", i, "a_" + IMPACTS[i])
	bt.add_node("splash_seek", _seek_node())
	bt.connect_node("splash_seek", 0, "splash_kind")
	# --- cart
	var cart := AnimationNodeBlendSpace1D.new()
	cart.min_space = -1.0
	cart.max_space = 1.0
	cart.sync = true
	# sim steer +1 = turning right
	cart.add_blend_point(_anim_node("cart_steer_l"), -1.0, -1, "steer_l")
	cart.add_blend_point(_anim_node("cart_drive"), 0.0, -1, "drive")
	cart.add_blend_point(_anim_node("cart_steer_r"), 1.0, -1, "steer_r")
	bt.add_node("cart_bs", cart)
	# --- state machine (as a Transition)
	var st := AnimationNodeTransition.new()
	st.xfade_time = 0.12
	var i := 0
	for s in STATES:
		st.add_input(s)
		st.set_input_reset(i, s != "ground")
		i += 1
		if s in ["ground", "air", "splash", "cart"]:
			continue
		bt.add_node("a_" + s, _anim_node(s))
	bt.add_node("state", st)
	i = 0
	for s in STATES:
		match s:
			"ground": bt.connect_node("state", i, "turn")
			"air": bt.connect_node("state", i, "air")
			"splash": bt.connect_node("state", i, "splash_seek")
			"cart": bt.connect_node("state", i, "cart_bs")
			_: bt.connect_node("state", i, "a_" + s)
		i += 1
	# --- overlays
	var fid := AnimationNodeTransition.new()
	fid.xfade_time = 0.0
	for f in FIDGETS:
		fid.add_input(f)
		bt.add_node("a_" + f, _anim_node(f))
	bt.add_node("fidget_pick", fid)
	for k in FIDGETS.size():
		bt.connect_node("fidget_pick", k, "a_" + FIDGETS[k])
	var fidget := AnimationNodeOneShot.new()
	fidget.fadein_time = 0.35
	fidget.fadeout_time = 0.4
	bt.add_node("fidget", fidget)
	bt.connect_node("fidget", 0, "state")
	bt.connect_node("fidget", 1, "fidget_pick")
	var prev := "fidget"
	for variant in ["f", "u"]:
		var mix := AnimationNodeBlend2.new()
		bt.add_node("land_mix_" + variant, mix)
		bt.add_node("a_land_soft_" + variant, _anim_node("land_soft"))
		bt.add_node("a_land_hard_" + variant, _anim_node("land_hard"))
		bt.connect_node("land_mix_" + variant, 0, "a_land_soft_" + variant)
		bt.connect_node("land_mix_" + variant, 1, "a_land_hard_" + variant)
		var os := AnimationNodeOneShot.new()
		os.fadein_time = 0.03
		os.fadeout_time = 0.16
		if variant == "u":
			_filtered(os)
		bt.add_node("land_" + variant, os)
		bt.connect_node("land_" + variant, 0, prev)
		bt.connect_node("land_" + variant, 1, "land_mix_" + variant)
		prev = "land_" + variant
	var rec := AnimationNodeOneShot.new()
	rec.fadein_time = 0.06
	rec.fadeout_time = 0.2
	_filtered(rec)
	bt.add_node("a_recover", _anim_node("recover"))
	bt.add_node("recover", rec)
	bt.connect_node("recover", 0, prev)
	bt.connect_node("recover", 1, "a_recover")
	bt.connect_node("output", 0, "recover")
	tree = AnimationTree.new()
	tree.name = "AnimTree"
	tree.tree_root = bt
	model.add_child(tree)
	tree.anim_player = tree.get_path_to(anim)
	tree.root_node = tree.get_path_to(anim.get_node(anim.root_node))
	tree.callback_mode_process = AnimationMixer.ANIMATION_CALLBACK_MODE_PROCESS_MANUAL
	tree.active = true
	_mode = ""
	_set_mode("ground")


func _build_effects() -> void:
	PropKit.init_meshes()
	dizzy = Node3D.new()
	dizzy.position = Vector3(0, 1.75, 0)
	add_child(dizzy)
	for k in 3:
		var a := TAU * float(k) / 3.0
		var s := MeshInstance3D.new()
		s.mesh = PropKit.sphere
		s.material_override = PropKit.mat(Color(1.0, 0.86, 0.35), 0.0, Color.WHITE, 1.2)
		s.position = Vector3(cos(a) * 0.32, 0, sin(a) * 0.32)
		s.scale = Vector3.ONE * 0.09
		s.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		dizzy.add_child(s)
	dizzy.visible = false
	bubble = MeshInstance3D.new()
	bubble.mesh = PropKit.sphere
	var bmat := StandardMaterial3D.new()
	bmat.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	bmat.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	bmat.albedo_color = Color(0.44, 0.85, 0.8, 0.14)
	bmat.cull_mode = BaseMaterial3D.CULL_BACK
	bubble.material_override = bmat
	bubble.scale = Vector3(1.4, 1.9, 1.4)
	bubble.position = Vector3(0, 0.85, 0)
	bubble.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	bubble.visible = false
	add_child(bubble)


func _ensure_drips() -> void:
	if drips != null:
		return
	drips = Fx.make_drip_emitter()
	drips.position = Vector3(0, 0.9, 0)
	add_child(drips)


func _build_flashlight() -> void:
	if flashlight != null:
		return
	var hand := skeleton.find_bone("hand.R")
	var att := BoneAttachment3D.new()
	att.bone_name = "hand.R"
	skeleton.add_child(att)
	# the flashlight mesh is built pointing along the model's forward (-Z)
	# at rest; keep the light aligned with it relative to the hand bone
	var lens_rest := Transform3D(Basis(), Vector3(0.409, 0.555, -0.105))
	var bone_rest := skeleton.get_bone_global_rest(hand)
	var holder := Node3D.new()
	holder.transform = bone_rest.affine_inverse() * lens_rest
	att.add_child(holder)
	flashlight = SpotLight3D.new()
	flashlight.light_color = Color(1.0, 0.95, 0.82)
	flashlight.light_energy = 2.6
	flashlight.spot_range = 20.0
	flashlight.spot_angle = 22.0
	flashlight.spot_attenuation = 0.9
	flashlight.shadow_enabled = false
	holder.add_child(flashlight)
	beam = MeshInstance3D.new()
	var bm := CylinderMesh.new()
	bm.top_radius = 0.05
	bm.bottom_radius = 2.4
	bm.height = 9.0
	bm.radial_segments = 16
	bm.cap_top = false
	bm.cap_bottom = false
	beam.mesh = bm
	var gm := ShaderMaterial.new()
	gm.shader = preload("res://assets/shaders/glow_add.gdshader")
	gm.set_shader_parameter("color", Color(1.0, 0.92, 0.72))
	gm.set_shader_parameter("intensity", 0.1)
	gm.set_shader_parameter("mode", 2.0)
	beam.material_override = gm
	beam.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	# CylinderMesh top (UV.y = 0, brightest in glow_add) sits at the lens
	beam.position = Vector3(0, 0, -4.6)
	beam.rotation = Vector3(PI * 0.5, 0, 0)
	holder.add_child(beam)


func _label_color() -> Color:
	return Color("ffc668") if role == TC.Role.PATROL else Color("f4f2ec")


func _build_label(display_name: String, is_bot: bool) -> void:
	if name_label == null:
		name_label = Label3D.new()
		add_child(name_label)
	# names are plain text (Label3D has no markup), already validated upstream
	name_label.text = (display_name + "  ·  BOT") if is_bot else display_name
	name_label.font = UIKit.font(true)
	name_label.font_size = 30
	name_label.outline_size = 10
	name_label.pixel_size = 0.0011
	name_label.billboard = BaseMaterial3D.BILLBOARD_ENABLED
	name_label.no_depth_test = false
	name_label.fixed_size = true
	name_label.position = Vector3(0, 2.05, 0)
	name_label.modulate = _label_color()
	name_label.outline_modulate = Color("11192b")
	name_label.visibility_range_end = 30.0
	name_label.visibility_range_end_margin = 8.0
	# right next to the camera the label would float high over the HUD, and
	# the player is plainly visible anyway
	name_label.visibility_range_begin = 3.5
	name_label.visibility_range_begin_margin = 1.0
	name_label.visibility_range_fade_mode = GeometryInstance3D.VISIBILITY_RANGE_FADE_SELF
	name_label.visible = not is_local and display_name != ""


func _apply_cosmetics() -> void:
	var patrol := role == TC.Role.PATROL
	var want: Array = []
	if patrol:
		want = ["base", "watch", "flashlight"]
		want.append_array(Cosmetics.entry("marks", cosmetic["marks"])["parts"])
		if int(Cosmetics.entry("color", cosmetic["color"])["id"]) % 2 == 1:
			want.append("mustache")
	else:
		want = Cosmetics.runner_parts(cosmetic)
	visible_parts.clear()
	for n in parts:
		var mi: MeshInstance3D = parts[n]
		mi.visible = n in want
		if mi.visible:
			visible_parts.append(mi)
	var t: Array = Cosmetics.tints(cosmetic)
	var stripes := 0.0 if patrol else Cosmetics.stripes_per_m(cosmetic)
	var rim := Color(1.0, 0.78, 0.55) if lighting == "indoor" else Color(0.55, 0.68, 1.0)
	for mi in visible_parts:
		mi.set_instance_shader_parameter("tint_primary", t[0])
		mi.set_instance_shader_parameter("tint_secondary", t[1])
		mi.set_instance_shader_parameter("tint_dark", t[2])
		mi.set_instance_shader_parameter("tint_skin", Cosmetics.skin_color(cosmetic))
		mi.set_instance_shader_parameter("tint_hair", Cosmetics.hair_color(cosmetic))
		mi.set_instance_shader_parameter("stripes", stripes)
		mi.set_instance_shader_parameter("rim_color", rim)
		mi.set_instance_shader_parameter("rim_strength", 0.14 if lighting == "indoor" else 0.1)
		mi.set_instance_shader_parameter("wet", _wet)
	_face_base = Cosmetics.face_keys(cosmetic)
	# nightcap tip spring only when it is worn
	var cap := not patrol and "hat_nightcap" in want
	if cap and hat_spring == null:
		hat_spring = SpringBoneSimulator3D.new()
		skeleton.add_child(hat_spring)
		hat_spring.setting_count = 1
		hat_spring.set_root_bone_name(0, "hat1")
		hat_spring.set_end_bone_name(0, "hat3")
		hat_spring.set_extend_end_bone(0, true)
		hat_spring.set_end_bone_length(0, 0.1)
		hat_spring.set_stiffness(0, 1.6)
		hat_spring.set_drag(0, 0.45)
		hat_spring.set_gravity(0, 0.4)
		hat_spring.set_radius(0, 0.03)
	if hat_spring:
		hat_spring.active = cap
	if patrol:
		_build_flashlight()
	if flashlight:
		flashlight.get_parent().visible = patrol


func set_flash(v: float, col: Color = Color.WHITE) -> void:
	for mi in visible_parts:
		mi.set_instance_shader_parameter("flash", v)
		mi.set_instance_shader_parameter("flash_color", col)


func _set_wet(v: float) -> void:
	if absf(v - _wet) < 0.01 and v > 0.0:
		return
	_wet = v
	for mi in visible_parts:
		mi.set_instance_shader_parameter("wet", v)


## Turn to look at a point (menus/lobby): yaw such that -Z points at `p`.
func face_toward(p: Vector3) -> void:
	var d := p - global_position
	rotation.y = atan2(-d.x, -d.z)
	_vis_yaw = rotation.y
	_have_yaw = true


## Set the facing directly (menus: placement, creator turntable), no easing.
func set_facing(yaw: float) -> void:
	rotation.y = yaw
	_vis_yaw = yaw
	_have_yaw = true
	rs["yaw"] = yaw


## Lobby departure: a wave, then shrink away and free (Reduced Motion: quick).
func play_leave() -> void:
	set_process(true)
	rs["emote"] = 0
	rs["emote_t"] = 1.0
	var tw := create_tween()
	tw.tween_interval(0.15 if reduced_motion else 0.7)
	tw.tween_property(self, "scale", Vector3.ONE * 0.01, 0.12 if reduced_motion else 0.25).set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_IN)
	tw.tween_callback(queue_free)


## One brief arrival hop (lobby).
func play_arrive() -> void:
	_arrive_t = 0.9


## Ready-up response (lobby).
func play_ready() -> void:
	_ready_t = 0.9


## The host said this Night Watch's lunge found nobody (TAG_MISS event).
func tag_missed() -> void:
	_miss_t = 0.5


## Hard reset of presentation history (respawn, teleport, cart entry/exit,
## reconnect, spectator switch): no lag/spring carries across the jump.
func reset_motion() -> void:
	_have_prev = false
	_have_yaw = false
	_prev_vel = Vector3.ZERO
	_squash = 0.0
	if secondary:
		secondary.reset_motion()
	if hat_spring:
		hat_spring.reset()


## rs keys: pos, yaw, vel, state, state_t, on_floor, diving, sprinting,
## tag_phase, protect, bump_protect, spotted, cart_id, steer, emote, emote_t,
## celebrate, show_finished, visible, impact.  The caller supplies render-time
## values (already interpolated); this view does not smooth position again.
func apply_state(state_rs: Dictionary, _delta: float = 0.0, snap: bool = false) -> void:
	rs = state_rs
	if rs.has("pos"):
		global_position = rs["pos"]
	if snap:
		reset_motion()
	if rs.has("yaw") and (snap or not _have_yaw):
		_vis_yaw = float(rs["yaw"])
		rotation.y = _vis_yaw
		_have_yaw = true


func _set_mode(m: String) -> void:
	if m == _mode or tree == null:
		return
	var st := tree.tree_root.get_node("state") as AnimationNodeTransition
	st.xfade_time = STATES.get(m, 0.12) * (0.5 if reduced_motion else 1.0)
	tree.set("parameters/state/transition_request", m)
	if _fidget_on:
		tree.set("parameters/fidget/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FADE_OUT)
		_fidget_on = false
	_mode = m
	_mode_t = 0.0


## Visual facing: follows the sim yaw closely but never snaps (aim-assist
## turns, snapshot gaps) and never spins the long way back during a reversal.
func _update_yaw(delta: float) -> float:
	var target := float(rs.get("yaw", rotation.y))
	if not _have_yaw:
		_vis_yaw = target
		_have_yaw = true
		_turn_sign = 0.0
		return 0.0
	var d := wrapf(target - _vis_yaw, -PI, PI)
	# around 180 degrees the shortest way can flip sides from frame to frame:
	# keep turning the way the turn started
	if absf(d) > 2.7 and _turn_sign != 0.0 and signf(d) != _turn_sign:
		d += TAU * _turn_sign
	if absf(d) > 0.05:
		_turn_sign = signf(d)
	elif absf(d) < 0.01:
		_turn_sign = 0.0
	var step := d * (1.0 - exp(-delta * 24.0))
	_vis_yaw = wrapf(_vis_yaw + step, -PI, PI)
	rotation.y = _vis_yaw
	return step


func _process(delta: float) -> void:
	if model == null or rs.is_empty():
		return
	_t += delta
	_mode_t += delta
	var st: int = rs.get("state", TC.PState.ACTIVE)
	var vel: Vector3 = rs.get("vel", Vector3.ZERO)
	var speed := Vector2(vel.x, vel.z).length()
	var on_floor: bool = rs.get("on_floor", true)
	var diving: bool = rs.get("diving", false)
	var sprinting: bool = rs.get("sprinting", false)
	var tag_phase: int = rs.get("tag_phase", 0)
	var state_t: float = rs.get("state_t", 0.0)
	var finished := st == TC.PState.FINISHED
	var captured := st == TC.PState.CAPTURED
	var emote: int = rs.get("emote", -1)
	var emote_t: float = rs.get("emote_t", 0.0)
	visible = not finished or bool(rs.get("show_finished", false))

	# --- facing + motion history (acceleration from the previous frame's velocity)
	var yaw_step := _update_yaw(delta)
	var accel := Vector3.ZERO
	var yaw_rate := 0.0
	if _have_prev and delta > 0.0:
		accel = (vel - _prev_vel) / delta
		yaw_rate = yaw_step / delta
	var entered_splash := false
	if st != _prev_state and _prev_state >= 0:
		# discontinuities: respawn after capture, splash resurfacing, cart in/out
		if _prev_state in [TC.PState.CAPTURED, TC.PState.SPLASHING, TC.PState.IN_CART, TC.PState.EXITING] or st == TC.PState.ENTERING:
			reset_motion()
			_vis_yaw = float(rs.get("yaw", rotation.y))
			rotation.y = _vis_yaw
			_have_yaw = true
			accel = Vector3.ZERO
			yaw_rate = 0.0
		if _prev_state == TC.PState.SPLASHING and st == TC.PState.ACTIVE:
			_on_resurface()
	if st == TC.PState.SPLASHING and (_prev_state != TC.PState.SPLASHING):
		entered_splash = true
	_prev_vel = vel
	_prev_yaw = rotation.y
	_have_prev = true
	_prev_state = st
	if secondary:
		secondary.accel = global_transform.basis.inverse() * accel
		secondary.turn_rate = yaw_rate
		secondary.speed = speed
		secondary.gain = 0.4 if reduced_motion else 1.0

	# --- landing / jump / dive edges (sounds + squash), debounced so a
	# prediction correction that flickers on_floor never doubles a sound
	var air := not on_floor and st == TC.PState.ACTIVE
	_since_land += delta
	_since_jump += delta
	if air:
		_air_t += delta
		_fall_speed = maxf(_fall_speed, -vel.y)
	if _prev_air and not air and st == TC.PState.ACTIVE:
		if _prev_diving or diving:
			_dive_land_t = 0.32
		elif _fall_speed > 2.5 and _air_t > 0.12 and _since_land > 0.25:
			_land(_fall_speed, speed)
		_fall_speed = 0.0
		_air_t = 0.0
	if not _prev_air and air and vel.y > 2.0 and st == TC.PState.ACTIVE and _since_jump > 0.3:
		_since_jump = 0.0
		_squash = -0.08
		if _near_camera(25.0):
			Sfx.play("jump", global_position, -6.0)
	if not air:
		_air_t = 0.0
	if diving and not _prev_diving and _near_camera(25.0):
		Sfx.play("dive", global_position, -4.0)
	_prev_air = air
	_prev_diving = diving
	_dive_land_t = maxf(0.0, _dive_land_t - delta)
	_arrive_t = maxf(0.0, _arrive_t - delta)
	_ready_t = maxf(0.0, _ready_t - delta)
	_miss_t = maxf(0.0, _miss_t - delta)
	_turn_cd = maxf(0.0, _turn_cd - delta)

	# --- choose the animation state
	var m := "ground"
	if st == TC.PState.ENTERING:
		m = "cart_enter"
	elif st == TC.PState.IN_CART:
		m = "cart"
	elif st == TC.PState.EXITING:
		m = "cart_exit"
	elif captured:
		m = "flop" if state_t < 0.9 else "dizzy"
	elif st == TC.PState.SPLASHING:
		m = "splash"
	elif st == TC.PState.STUMBLE:
		m = "stumble"
	elif finished or bool(rs.get("celebrate", false)):
		m = "celebrate"
	elif diving:
		m = "dive"
	elif _dive_land_t > 0.0:
		m = "dive_land"
	elif tag_phase == 1:
		m = "tag_windup"
	elif tag_phase == 2:
		m = "tag_lunge"
	elif tag_phase == 3:
		m = "tag_miss" if _miss_t > 0.0 else "tag_recover"
	elif air:
		m = "air"
	elif emote >= 0 and emote_t > 0.0 and speed < 1.0:
		m = "emote_" + TC.EMOTES[emote]
	elif _ready_t > 0.0:
		m = "ready"
	elif _arrive_t > 0.0:
		m = "arrive"
	_set_mode(m)

	# --- per-state parameters
	var idle_t := fmod(_t + _idle_off, IDLE_LEN)
	tree.set("parameters/idle_seek/seek_request", idle_t)
	if m == "ground":
		_update_ground(delta, speed, on_floor, sprinting, yaw_rate)
	else:
		_still_t = 0.0
		tree.set("parameters/loco_seek/seek_request", fposmod(_phase, 1.0))
	if m == "air":
		tree.set("parameters/air/blend_position", clampf(vel.y, AIR_POINTS["air_fall"], AIR_POINTS["air_rise"]))
	elif m == "cart":
		tree.set("parameters/cart_bs/blend_position", clampf(float(rs.get("steer", 0.0)), -1.0, 1.0))
	if st == TC.PState.SPLASHING:
		_update_splash(delta, state_t, entered_splash)
	else:
		_splash_t = -1.0

	# --- squash & stretch (scale about the feet), small and fast
	_squash = move_toward(_squash, 0.0, delta * 1.2)
	var sq := _squash * (0.4 if reduced_motion else 1.0)
	model.scale = Vector3(1.0 + sq * 0.5, 1.0 - sq, 1.0 + sq * 0.5)

	# --- effects
	dizzy.visible = captured and state_t > 0.5 and state_t < 4.5
	if dizzy.visible:
		dizzy.rotation.y += delta * 5.0
	bubble.visible = float(rs.get("protect", 0.0)) > 0.0 and not captured
	if bubble.visible:
		(bubble.material_override as StandardMaterial3D).albedo_color.a = 0.10 + 0.06 * sin(_t * 10.0)
	if flashlight:
		var show_light := role == TC.Role.PATROL and m != "cart" and m != "cart_enter"
		flashlight.visible = show_light
		beam.visible = show_light
	var flash := 0.0
	if float(rs.get("protect", 0.0)) > 0.0:
		flash = 0.18 + 0.14 * sin(_t * 16.0)
	elif float(rs.get("bump_protect", 0.0)) > 0.0:
		flash = 0.15
	set_flash(flash, Color("6fd8cc"))
	if _wet > 0.0 and st != TC.PState.SPLASHING:
		_set_wet(maxf(0.0, _wet - delta / 5.0))
	if drips:
		_drip_t = maxf(0.0, _drip_t - delta)
		drips.emitting = _drip_t > 0.0 and visible

	# --- face
	_update_face(delta, m, sprinting, tag_phase, bool(rs.get("spotted", false)))

	# --- animate (manual advance: distant characters update at a lower rate,
	# with the real elapsed time accumulated so they keep the right pace)
	if not tree.active:
		return
	var far := not is_local and not _near_camera(45.0)
	_anim_acc += delta
	_anim_skip += 1
	if not far or _anim_skip >= 3:
		tree.advance(_anim_acc)
		anim_time_advanced += _anim_acc
		_anim_acc = 0.0
		_anim_skip = 0


func _update_ground(delta: float, speed: float, on_floor: bool, sprinting: bool, yaw_rate: float) -> void:
	var bs := clampf(speed, LOCO_POINTS["walk"], LOCO_POINTS["sprint"])
	var mpc := _m_per_cycle(bs)
	var rate := speed / mpc if speed > 0.05 else 0.0
	tree.set("parameters/loco/blend_position", bs)
	tree.set("parameters/move/blend_amount", smoothstep(0.15, 0.9, speed))
	_phase += delta * rate
	tree.set("parameters/loco_seek/seek_request", fposmod(_phase, 1.0))
	# footsteps at the gait's own foot strikes (left at 1 - duty/2, right at
	# 0.5 - duty/2 of the cycle): the sound is where the foot meets the ground
	var duty := _duty(bs)
	var k := int(floor((_phase + duty * 0.5) * 2.0))
	if not _step_init:
		_step_k = k   # start counting from the current phase (no phantom step)
		_step_init = true
	if k != _step_k:
		if on_floor and speed > 1.0 and k > _step_k and _near_camera(30.0):
			var walk := speed < 3.0
			var db := (-12.0 if walk else -6.0) + (4.0 if sprinting else 0.0) + (2.0 if role == TC.Role.PATROL else 0.0)
			Sfx.play("step", global_position, db, 0.9 if role == TC.Role.PATROL else 1.1)
		_step_k = k
	# turn in place
	if speed < 0.4:
		_yaw_accum += yaw_rate * delta
		_yaw_accum *= exp(-delta * 4.0)
		if absf(_yaw_accum) > 0.5 and _turn_cd <= 0.0:
			tree.set("parameters/turn_dir/transition_request", "l" if _yaw_accum > 0.0 else "r")
			tree.set("parameters/turn/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)
			_turn_cd = 0.45
			_yaw_accum = 0.0
	else:
		_yaw_accum = 0.0
	# idle fidgets
	if fidgets and speed < 0.1 and float(rs.get("emote_t", 0.0)) <= 0.0 and _arrive_t <= 0.0 and _ready_t <= 0.0:
		_still_t += delta
		if _still_t > _next_fidget:
			_still_t = 0.0
			_next_fidget = _rng.randf_range(8.0, 16.0)
			tree.set("parameters/fidget_pick/transition_request", FIDGETS[_rng.randi() % FIDGETS.size()])
			tree.set("parameters/fidget/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)
			_fidget_on = true
	else:
		_still_t = 0.0
		if _fidget_on and speed > 0.3:
			tree.set("parameters/fidget/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FADE_OUT)
			_fidget_on = false


func _land(fall_speed: float, speed: float) -> void:
	_since_land = 0.0
	var hard := clampf(inverse_lerp(4.0, 11.0, fall_speed), 0.0, 1.0)
	var which := "u" if speed > 1.5 else "f"
	tree.set("parameters/land_mix_%s/blend_amount" % which, hard)
	tree.set("parameters/land_%s/request" % which, AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)
	_squash = clampf(fall_speed * 0.018, 0.05, 0.18) * (0.7 if speed > 1.5 else 1.0)
	if _near_camera(25.0):
		Sfx.play("land", global_position, -8.0 + 5.0 * hard)


## Splash choreography clock: starts at the authoritative state_t (so a late
## joiner enters at the right beat), advances with real frame time between
## snapshots and re-syncs if it drifts.
func _update_splash(delta: float, state_t: float, entered: bool) -> void:
	if entered or _splash_t < 0.0:
		_splash_t = state_t
		_splash_beats = 0
		_splash_pos = global_position
		_splash_kind = clampi(int(rs.get("impact", 0)), 0, IMPACTS.size() - 1)
		tree.set("parameters/splash_kind/transition_request", str(_splash_kind))
		_set_wet(1.0)
	else:
		_splash_t += delta
		if absf(_splash_t - state_t) > 0.15:
			_splash_t = state_t
	var t := clampf(_splash_t, 0.0, SPLASH_LEN)
	tree.set("parameters/splash_seek/seek_request", t)
	_splash_beat_fx(t)


## Splash FX beats, each at most once per splash.  A late joiner who first
## sees the runner mid-sequence skips the beats that already happened.
func _splash_beat_fx(t: float) -> void:
	if fx == null or not visible:
		return
	var w: Dictionary = water_at.call(_splash_pos) if water_at.is_valid() else {}
	var beats := [
		[0, 0.0, 0.25], [1, 0.42, 0.6], [2, 0.75, 0.95], [3, 1.02, 1.2], [4, 1.36, 1.5],
	]
	for b in beats:
		var bit := 1 << int(b[0])
		if (_splash_beats & bit) != 0 or t < float(b[1]):
			continue
		_splash_beats |= bit
		if t > float(b[2]):
			continue   # joined after this beat
		match int(b[0]):
			0:
				fx.splash_impact(_splash_pos, _splash_kind, w.get("color", Color(0.6, 0.85, 1.0)), reduced_motion)
				fx.ripple(w, _splash_pos, 1.0)
				if _near_camera(40.0):
					Sfx.play("splash_big" if bool(rs.get("stamped", false)) else "splash", _splash_pos)
			1:
				fx.ripple(w, _splash_pos, 0.55)
			2, 3:
				fx.ripple(w, _splash_pos, 0.3)
			4:
				fx.ripple(w, _splash_pos, 0.6)
				fx.duck_under(_splash_pos, reduced_motion)


func _on_resurface() -> void:
	tree.set("parameters/recover/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)
	_set_wet(1.0)
	_ensure_drips()
	_drip_t = 1.4 if not reduced_motion else 0.8
	if fx and visible:
		fx.shore_pop(global_position, reduced_motion)


func _m_per_cycle(bs: float) -> float:
	if bs <= LOCO_POINTS["run"]:
		return lerpf(LOCO_M_PER_CYCLE["walk"], LOCO_M_PER_CYCLE["run"], inverse_lerp(LOCO_POINTS["walk"], LOCO_POINTS["run"], bs))
	return lerpf(LOCO_M_PER_CYCLE["run"], LOCO_M_PER_CYCLE["sprint"], inverse_lerp(LOCO_POINTS["run"], LOCO_POINTS["sprint"], bs))


func _duty(bs: float) -> float:
	if bs <= LOCO_POINTS["run"]:
		return lerpf(LOCO_DUTY["walk"], LOCO_DUTY["run"], inverse_lerp(LOCO_POINTS["walk"], LOCO_POINTS["run"], bs))
	return lerpf(LOCO_DUTY["run"], LOCO_DUTY["sprint"], inverse_lerp(LOCO_POINTS["run"], LOCO_POINTS["sprint"], bs))


## Gait cycles per second at a ground speed (for tests and tools).
static func gait_rate(speed: float) -> float:
	var v := CharacterView.new()
	var bs := clampf(speed, LOCO_POINTS["walk"], LOCO_POINTS["sprint"])
	var r := speed / v._m_per_cycle(bs)
	v.free()
	return r


func _update_face(delta: float, m: String, sprinting: bool, tag_phase: int, spotted: bool) -> void:
	var tgt := {"blink": 0.0, "squint": 0.0, "smile": 0.0, "open": 0.0, "brow_up": 0.0, "brow_angry": 0.0}
	match m:
		"celebrate", "emote_cheer", "emote_laugh", "emote_dance", "arrive", "ready":
			tgt["squint"] = 1.0
			tgt["smile"] = 1.0
			tgt["open"] = 0.55
		"splash":
			# surprise on impact, puffed-cheek calm while treading, a breath before ducking
			var t := _splash_t
			if t < 0.45:
				tgt["open"] = 0.9
				tgt["brow_up"] = 1.0
			elif t < 1.15:
				tgt["smile"] = 0.3
				tgt["brow_up"] = 0.4
			else:
				tgt["open"] = 0.7
				tgt["squint"] = 0.6
		"air":
			var vy := float((rs.get("vel", Vector3.ZERO) as Vector3).y)
			tgt["open"] = 0.5 if vy < -4.0 else 0.2
			tgt["smile"] = 0.5 if vy > 0.0 else 0.0
			tgt["brow_up"] = 0.6 if vy < -4.0 else 0.2
		"stumble", "flop":
			tgt["open"] = 0.85
			tgt["brow_up"] = 1.0
		"dizzy":
			tgt["squint"] = 0.6
			tgt["open"] = 0.3
			tgt["brow_up"] = 0.5
		"tag_windup", "tag_lunge", "dive":
			tgt["brow_angry"] = 1.0
			tgt["open"] = 0.35
		"tag_miss":
			tgt["brow_up"] = 0.9
			tgt["open"] = 0.5
		"emote_wave", "emote_point":
			tgt["smile"] = 0.9
			tgt["open"] = 0.3
		"emote_shrug":
			tgt["brow_up"] = 0.8
		_:
			tgt["smile"] = 0.35
			if sprinting or tag_phase > 0:
				tgt["brow_angry"] = 0.8
				tgt["smile"] = 0.0
	if _fidget_on:
		tgt["open"] = 0.8
		tgt["squint"] = 0.7
	if _drip_t > 0.0:
		tgt["squint"] = maxf(float(tgt["squint"]), 0.7)
	if spotted:
		tgt["brow_up"] = 1.0
		tgt["open"] = maxf(float(tgt["open"]), 0.6)
		tgt["smile"] = 0.0
	# blinking (never while squinting)
	_blink_t -= delta
	if _blink_t <= 0.0:
		_blink_t = _rng.randf_range(2.2, 4.6)
		_blink = 0.13
	_blink = maxf(0.0, _blink - delta)
	if _blink > 0.0 and float(tgt["squint"]) < 0.5:
		tgt["blink"] = 1.0
	var k := 1.0 - exp(-delta * 18.0)
	for key in _face:
		var target: float = float(tgt.get(key, 0.0))
		var cur := float(_face[key])
		_face[key] = target if key == "blink" else lerpf(cur, target, k)
		var w := minf(1.0, float(_face[key]) + float(_face_base.get(key, 0.0)))
		base_mesh.set_blend_shape_value(_face_idx[key], w)


func _near_camera(r: float) -> bool:
	var cam := get_viewport().get_camera_3d() if is_inside_tree() else null
	return cam != null and cam.global_position.distance_to(global_position) < r
