class_name CharacterArt
## Generated by tools/character/build_character.py with runner.glb: do not edit.
## The character art version: the asset generation and the GLB's SHA-256.
## Portraits.key_of includes it, so thumbnails of an older asset are never
## reused (test_portraits checks it matches runner_manifest.json and the GLB).

const VERSION := "v10-8aa7d2363cbe"
const GLB_SHA256 := "8aa7d2363cbeb336200a318f933d9bf684e7381d0a0e6e1fa3d35010ca663fc2"
