class_name CharacterArt
## Generated by tools/character/build_character.py with runner.glb: do not edit.
## The character art version: the asset generation and the GLB's SHA-256.
## Portraits.key_of includes it, so thumbnails of an older asset are never
## reused (test_portraits checks it matches runner_manifest.json and the GLB).

const VERSION := "v8-528149faa87b"
const GLB_SHA256 := "528149faa87b788aa07dcbe42cd73baec922d86389baf210f76cbe3d8ec5e695"
