class_name CharacterArt
## Generated by tools/character/build_character.py with runner.glb: do not edit.
## The character art version: the asset generation and the GLB's SHA-256.
## Portraits.key_of includes it, so thumbnails of an older asset are never
## reused (test_portraits checks it matches runner_manifest.json and the GLB).

const VERSION := "v10-b3127262ef43"
const GLB_SHA256 := "b3127262ef4331665153534705921e800497b9cc31f8865ac3a17b775927469a"
