class_name CharacterView
extends Node3D
## The skinned Trifecta runner / Night Watch character (one shared asset:
## assets/characters/runner.glb, generated by tools/character/build_character.py).
## Used identically by gameplay, lobby, creator, home and results.
##
## Presentation only: it shows authoritative/interpolated state and never
## moves gameplay (the gameplay capsule lives in the sim).  Nothing here
## changes speed, reach, immunity, objective credit or action timing.
##
## Forward convention: at yaw 0 the character faces -Z, the same as the sim's
## yaw (forward = Basis(UP, yaw) * -Z) and Godot cameras.  Use face_toward()
## to turn a character to the camera in menu scenes.
##
## Animation graph (built per instance, advanced manually at the end of
## _process so the state chosen this frame is the pose drawn this frame):
##   ground  = idle (seeked, per-instance offset) <-> locomotion blend space
##             (walk/run/sprint, seeked to this view's gait phase) + a
##             turn-in-place one-shot
##   air     = blend space over vertical velocity (rise / apex / fall), so the
##             top of a jump never pops
##   splash  = one of three impact clips seeked to the runner's authoritative
##             time in the water (a late joiner sees the right beat)
##   others  = Transition states (dive, tag, cart, celebrate, emotes, ...)
##   overlays: an upper-body action layer (tag wind-up / recovery while the
##             legs keep running), full-body and upper-body landing one-shots
##             (soft/hard mix), an upper-body recovery shake-off (legs keep
##             running) and idle fidgets.
## CharacterPoseFade (first skeleton modifier) makes every state change start
## from the pose on screen, so interrupted cross-fades never snap (V5).
## CharacterSecondary adds head lag, body lean and banking; a spring-bone
## chain moves the nightcap tip.  Face shapes are blend shapes on the head
## that is shown: "base", or (Pass 9) a complete skin's own head (face_mesh).
##
## V5 motion notes (docs/v5/motion_notes.md):
##  * Locomotion weight and blend-space speed are smoothed in time (the sim
##    reaches full speed in ~0.1 s, which used to swap whole poses in 1-2
##    frames).  Starts begin on a step; stops finish the step they are in.
##  * Gait cadence: rate = forward ground speed / metres per cycle of the
##    pose actually shown, so planted feet stay planted while the blend moves.
##  * Visual air needs ~0.07 s off the floor (or a real jump), so a floor
##    contact flicker never plays half a jump.
##  * Teleports (respawn, resurfacing, cart seat in/out) cut the pose; any
##    other state change fades from the displayed pose.
##  * Secondary motion reads a filtered acceleration (bounded by velocity
##    change / ACC_TAU, independent of the render delta).
##  * Menu idle (set_menu_idle, on by default for lighting "indoor"): slower
##    breathing, restrained fidgets, softer blinks, a calmer nightcap.
##  * Animation LOD has hysteresis (LOD_FAR / LOD_NEAR).

const SCENE := preload("res://assets/characters/runner.glb")
const SHADER := preload("res://assets/shaders/character.gdshader")
const SHADER_TWO_SIDED := preload("res://assets/shaders/character_two_sided.gdshader")
## Parts drawn without back-face culling: the nightcap's fold crosses itself
## (tools/character/parts.py build_nightcap), and culled it showed the head
## through the crease.
const TWO_SIDED := ["hat_nightcap"]

## m/s at which each locomotion clip is blended in (blend-space positions)
const LOCO_POINTS := {"walk": 1.3, "run": 5.0, "sprint": 7.0}
## metres per 1.0 s cycle at rate 1 and stance fraction (runner_manifest.json,
## tools/character/anims.py LOCO).  gait rate = speed / metres-per-cycle.
const LOCO_M_PER_CYCLE := {"walk": 0.70, "run": 2.20, "sprint": 2.75}
const LOCO_DUTY := {"walk": 0.58, "run": 0.20, "sprint": 0.165}
const IDLE_LEN := 4.0
const SPLASH_LEN := 1.5
## air blend space positions (vertical m/s)
const AIR_POINTS := {"air_fall": -7.0, "air_apex": 0.0, "air_rise": 5.5}
## impact class carried by the splash (sim: SimPlayer.splash_impact)
const IMPACTS := ["splash_walk", "splash_jump", "splash_dive"]

const HAIR_BY_SKIN := [Color("4a3222"), Color("2e1e15"), Color("1f1712"), Color("151010"), Color("b8743f")]

## state name -> xfade seconds into that state
const STATES := {
	"ground": 0.16, "air": 0.1, "dive": 0.1, "dive_land": 0.08, "splash": 0.1,
	"stumble": 0.06, "flop": 0.1, "dizzy": 0.3, "tag_windup": 0.05, "tag_lunge": 0.04, "tag_recover": 0.08, "tag_miss": 0.08,
	"cart_enter": 0.08, "cart": 0.12, "cart_exit": 0.06, "celebrate": 0.15, "arrive": 0.05, "ready": 0.08,
	"emote_wave": 0.15, "emote_cheer": 0.15, "emote_laugh": 0.15, "emote_shrug": 0.15, "emote_dance": 0.15, "emote_point": 0.15,
	"emote_stargaze": 0.2, "emote_victory_lap": 0.15, "emote_shush": 0.15, "emote_moon_shuffle": 0.15,
}
const UPPER_BODY := ["spine", "chest", "neck", "head", "shoulder.L", "shoulder.R", "upper_arm.L", "upper_arm.R",
	"forearm.L", "forearm.R", "hand.L", "hand.R"]
const FIDGETS := ["fidget_yawn", "fidget_look", "fidget_shift", "fidget_bounce"]
## gameplay idles pick from these; menus from MENU_FIDGETS (weights)
const GAME_FIDGETS := {"fidget_yawn": 1.0, "fidget_look": 1.0}
const MENU_FIDGETS := {"fidget_look": 3.0, "fidget_shift": 3.0, "fidget_bounce": 2.0, "fidget_yawn": 1.0}
## upper-body action layer clips (tag wind-up and recovery while running)
const ACTS := ["tag_windup", "tag_recover", "tag_miss"]
## speed above which tag wind-up / recovery play on the upper body only
const ACT_RUN_SPEED := 1.2
## secondary motion: velocity filter (s) and acceleration bound (m/s^2)
const ACC_TAU := 0.05
const ACC_MAX := 55.0
## a state discontinuity that moved the character further than this in one
## frame is a teleport: the pose cuts instead of fading
const CUT_DIST := 0.5
## animation LOD: throttled beyond LOD_FAR, full rate again inside LOD_NEAR
const LOD_FAR := 48.0
const LOD_NEAR := 42.0
## nightcap inertia: spring-bone force per m/s^2 of body acceleration (the
## spring runs in the character's own space, so translation, yaw, hitches
## and teleports never fling it; inertia comes only from this force)
const HAT_INERTIA := 0.025
const HAT_FORCE_MAX := 1.4
## visual air state: seconds off the floor before it shows (unless rising)
const AIR_DEBOUNCE := 0.07
## blend-space speed filter (s)
const BS_TAU := 0.03
const EXPRESSIONS := ["blink", "squint", "smile", "open", "brow_up", "brow_angry"]

static var _material: ShaderMaterial
static var _material_two_sided: ShaderMaterial

var role: int = TC.Role.RUNNER
var cosmetic: Dictionary = Cosmetics.DEFAULT
var slot: int = -1
var is_local := false
var reduced_motion := false
## idle fidgets (yawn, look around) after standing still for a while
var fidgets := true
var rs: Dictionary = {}
## "outdoor" (cool moon rim) or "indoor" (warm lamp rim); set before setup()
var lighting := "outdoor"
## optional: the match's Fx node and a water lookup (pos -> {mat, center,
## color}) for splash beats; left empty in menus
var fx: Fx
var water_at: Callable

## menus: calmer idle (see set_menu_idle); automatic for lighting "indoor"
var menu_idle := false
var _menu_idle_set := false

var model: Node3D
var skeleton: Skeleton3D
var anim: AnimationPlayer
var tree: AnimationTree
var secondary: CharacterSecondary
var pose_fade: CharacterPoseFade
## V6: pins the stance foot in turns, stops and reversals (CharacterFootLock)
var foot_lock: CharacterFootLock
var hat_spring: SpringBoneSimulator3D
var parts: Dictionary = {}          # name -> MeshInstance3D
var visible_parts: Array[MeshInstance3D] = []
var base_mesh: MeshInstance3D
## Pass 9: the head whose face shapes play ("base" or a complete skin's head)
var face_mesh: MeshInstance3D
var _face_idx_of := {}          # head part -> {shape name: blend shape index}
var name_label: Label3D
var flashlight: SpotLight3D
var beam: MeshInstance3D
var dizzy: Node3D
var bubble: MeshInstance3D
var drips: CPUParticles3D

var _mode := ""
var _mode_t := 0.0
var _prev_state := -1
var _prev_air := false
var _prev_diving := false
var _prev_vel := Vector3.ZERO
var _have_prev := false
var _vis_yaw := 0.0
var _have_yaw := false
var _turn_sign := 0.0
var _fall_speed := 0.0
var _air_t := 0.0
var _since_land := 9.0
var _since_jump := 9.0
var _dive_land_t := 0.0
const DIVE_LAND_S := 0.45      # == RulesConfig.dive_land_s and the dive_land clip (Pass 8 landing recovery)
var _arrive_t := 0.0
var _ready_t := 0.0
var _miss_t := 0.0
var _turn_cd := 0.0
var _yaw_accum := 0.0
var _phase := 0.0
var _step_k := 0
var _step_init := false
var _idle_off := 0.0
var _still_t := 0.0
var _next_fidget := 8.0
var _fidget_on := false
var _splash_t := -1.0
var _splash_kind := 0
var _splash_beats := 0
var _splash_pos := Vector3.ZERO
var _wet := 0.0
var _drip_t := 0.0
var _drip_show_t := 0.0
var _blink_t := 2.0
var _blink := 0.0
var _rng := RandomNumberGenerator.new()
var _face := {}
var _face_base := {}
var _face_idx := {}
var _squash := 0.0
var _t := 0.0
## V8: distant characters' animation clock (see _process_view)
const FAR_ANIM_STEP := 1.0 / 20.0
var _far_clock := 0.0
var _far_stagger := 0.0
var _face_acc := 0.0
var _anim_acc := 0.0
# V5 motion state
var _move_w := 0.0            # locomotion weight shown (0 idle .. 1 moving)
var _bs := 1.3                # blend-space speed shown (m/s)
var _settle_to := -1.0        # stopping: gait phase the step settles on
var _vel_f := Vector3.ZERO    # filtered velocity (secondary acceleration)
var _air_hold := 0.0
var _air_vis := false
var _cut := false
var _last_pos := Vector3.ZERO
var _have_last := false       # _last_pos is a real previous position
var _cam_d := INF
var _far := false
var _act := ""
var _act_w := 0.0
var _idle_clock := 0.0
var _squash_v := 0.0
var _fidget := ""
var _blink_len := 0.16
var _hat_off := false
var _travel_f := Vector3.ZERO
var _last_base := Vector3.ZERO
var _spot_t := 0.0            # how long the character has run without travelling
# V8 authored transitions (drive / brake / turn lead layers, planted stop)
const ACCEL_REF := 30.0       # m/s^2 of forward acceleration that shows the full drive pose
const STOP_FROM := 3.0        # m/s: a stop from at least this pace plants
var _fwd_acc := 0.0           # filtered forward acceleration (m/s^2, + = speeding up)
var _fwd_acc_f := 0.0         # slower, for the drive/brake layers
const ACCEL_DEAD := 8.0       # m/s^2 of filtered acceleration the layers ignore
const BRAKE_REF := 20.0       # filtered deceleration that shows the brake fully (a stop from a run: ~23)
var _start_t := 9.0           # since the gait began from a standstill
var _accel_w := 0.0
var _brake_w := 0.0
var _brake_hold := 0.0        # the brake weight when the planted stop fired
var _lead_w := 0.0
var _lead_sign := 0.0
var _lead_pos := 0.0          # shown side (-1 right .. +1 left), eased (never flips in a frame)
var _run_mem := 0.0           # recent ground speed (decays), for stop planting
var _stop_on := false
var _stop_t := 0.0
const STOP_LEN := 0.5         # == anims.STOP_L
var stat_stops := 0           # planted stops played (tests)
## V8: set by the match controller: feet follow the real ground (steps, ramps)
var terrain_contact := false
var ground_fn: Callable       # tests: an analytic ground instead of the physics ray
## total animation time advanced (tests: equals the real elapsed time)
var anim_time_advanced := 0.0


static func _shared_material(two_sided: bool = false) -> ShaderMaterial:
	if two_sided:
		if _material_two_sided == null:
			_material_two_sided = ShaderMaterial.new()
			_material_two_sided.shader = SHADER_TWO_SIDED
		return _material_two_sided
	if _material == null:
		_material = ShaderMaterial.new()
		_material.shader = SHADER
	return _material


func setup(p_role: int, p_cosmetic: Dictionary, p_slot: int, display_name: String, is_bot: bool, local: bool = false) -> void:
	role = p_role
	cosmetic = Cosmetics.sanitize(p_cosmetic)
	slot = p_slot
	is_local = local
	_rng.seed = hash(str(p_slot) + display_name + str(get_instance_id()))
	_far_stagger = fposmod(float(maxi(p_slot, 0)) * 0.381966, 1.0)
	_far_clock = _far_stagger * FAR_ANIM_STEP
	_idle_off = _rng.randf() * IDLE_LEN
	_idle_clock = _idle_off
	_phase = _rng.randf()
	_next_fidget = _rng.randf_range(6.0, 14.0)
	_blink_t = _rng.randf_range(0.5, 3.0)
	if not _menu_idle_set:
		menu_idle = lighting == "indoor"
	if model == null:
		_build_model()
	_apply_cosmetics()
	_build_label(display_name, is_bot)


## Menus (dorm lobby, home, wardrobe/creator preview): a calmer idle for a
## screen people read.  Idle breathing slows a little, fidgets are restrained
## ones (look around, shift weight, a small heel bounce, the odd yawn) every
## 7-12 s, blinks are softer with the occasional double blink, and the
## nightcap spring is stiffer and better damped.  Emotes, arrivals, ready
## responses and "Try moves" are unchanged.  On by default when `lighting`
## is "indoor" (every menu stage); call this to override either way.
func set_menu_idle(on: bool) -> void:
	_menu_idle_set = true
	if on == menu_idle:
		return
	menu_idle = on
	_still_t = 0.0
	_next_fidget = _rng.randf_range(5.0, 9.0) if on else _rng.randf_range(8.0, 16.0)
	_apply_hat_tuning()


## Change outfit/role in place (no rebuild; used by lobby and creator).
func set_appearance(p_role: int, p_cosmetic: Dictionary) -> void:
	role = p_role
	cosmetic = Cosmetics.sanitize(p_cosmetic)
	if model != null:
		_apply_cosmetics()
		if name_label:
			name_label.modulate = _label_color()


func _build_model() -> void:
	model = SCENE.instantiate()
	add_child(model)
	skeleton = model.find_children("*", "Skeleton3D", true, false)[0]
	anim = model.find_children("*", "AnimationPlayer", true, false)[0]
	for c in skeleton.get_children():
		if c is MeshInstance3D:
			var mi := c as MeshInstance3D
			parts[String(mi.name)] = mi
			mi.material_override = _shared_material(TWO_SIDED.has(String(mi.name)))
			mi.visible = false
	base_mesh = parts.get("base")
	for n in parts:
		var hm := (parts[n] as MeshInstance3D).mesh
		if hm.get_blend_shape_count() > 0:
			var idx := {}
			for i in hm.get_blend_shape_count():
				idx[String(hm.get_blend_shape_name(i))] = i
			_face_idx_of[n] = idx
	face_mesh = base_mesh
	_face_idx = _face_idx_of["base"]
	for k in _face_idx:
		_face[k] = 0.0
	_prepare_animations()
	# modifier order: pose fade (sees the raw animation), then secondary
	# motion, then the nightcap spring (added with the cosmetics)
	pose_fade = CharacterPoseFade.new()
	pose_fade.name = "PoseFade"
	skeleton.add_child(pose_fade)
	secondary = CharacterSecondary.new()
	skeleton.add_child(secondary)
	foot_lock = CharacterFootLock.new()
	foot_lock.name = "FootLock"
	skeleton.add_child(foot_lock)
	_build_tree()
	_build_effects()


func _prepare_animations() -> void:
	# loop flags come from the asset manifest; the library resource is shared
	# by every instance, so this runs once per resource
	var lib := anim.get_animation_library("")
	if lib == null or lib.has_meta("ut_prepared"):
		return
	for n in lib.get_animation_list():
		var a := lib.get_animation(n)
		var looped := String(n) in ["idle", "walk", "run", "sprint", "air_rise", "air_apex", "air_fall", "dizzy",
			"cart_drive", "cart_steer_l", "cart_steer_r", "celebrate"] or String(n).begins_with("emote_")
		a.loop_mode = Animation.LOOP_LINEAR if looped else Animation.LOOP_NONE
	lib.set_meta("ut_prepared", true)


func _anim_node(n: String) -> AnimationNodeAnimation:
	var a := AnimationNodeAnimation.new()
	a.animation = n
	return a


func _seek_node() -> AnimationNodeTimeSeek:
	var s := AnimationNodeTimeSeek.new()
	s.explicit_elapse = false
	return s


func _filtered(n: AnimationNode) -> void:
	n.filter_enabled = true
	var root_path := String(anim.get_parent().get_path_to(skeleton)) if anim.get_parent() else "Runner/Skeleton3D"
	for b in UPPER_BODY:
		n.set_filter_path(NodePath(root_path + ":" + b), true)


func _build_tree() -> void:
	var bt := AnimationNodeBlendTree.new()
	# --- ground: idle (seeked) <-> loco (seeked to the gait phase)
	bt.add_node("a_idle", _anim_node("idle"))
	bt.add_node("idle_seek", _seek_node())
	bt.connect_node("idle_seek", 0, "a_idle")
	var loco := AnimationNodeBlendSpace1D.new()
	loco.min_space = 0.0
	loco.max_space = 9.0
	loco.sync = true
	for k in LOCO_POINTS:
		loco.add_blend_point(_anim_node(k), LOCO_POINTS[k], -1, k)
	bt.add_node("loco", loco)
	bt.add_node("loco_seek", _seek_node())
	bt.connect_node("loco_seek", 0, "loco")
	var move := AnimationNodeBlend2.new()
	bt.add_node("move", move)
	bt.connect_node("move", 0, "idle_seek")
	bt.connect_node("move", 1, "loco_seek")
	var tdir := AnimationNodeTransition.new()
	tdir.add_input("l")
	tdir.add_input("r")
	tdir.xfade_time = 0.0
	bt.add_node("turn_dir", tdir)
	bt.add_node("turn_l", _anim_node("turn_l"))
	bt.add_node("turn_r", _anim_node("turn_r"))
	bt.connect_node("turn_dir", 0, "turn_l")
	bt.connect_node("turn_dir", 1, "turn_r")
	# V8: planted stop (a one-shot over the gait/idle blend, from running)
	var sdir := AnimationNodeTransition.new()
	sdir.add_input("l")
	sdir.add_input("r")
	sdir.xfade_time = 0.0
	bt.add_node("stop_dir", sdir)
	bt.add_node("a_stop_l", _anim_node("stop_l"))
	bt.add_node("a_stop_r", _anim_node("stop_r"))
	bt.connect_node("stop_dir", 0, "a_stop_l")
	bt.connect_node("stop_dir", 1, "a_stop_r")
	var stop := AnimationNodeOneShot.new()
	stop.fadein_time = 0.1
	stop.fadeout_time = 0.15
	bt.add_node("stop", stop)
	bt.connect_node("stop", 0, "move")
	bt.connect_node("stop", 1, "stop_dir")
	var turn := AnimationNodeOneShot.new()
	turn.fadein_time = 0.08
	turn.fadeout_time = 0.12
	bt.add_node("turn", turn)
	bt.connect_node("turn", 0, "stop")
	bt.connect_node("turn", 1, "turn_dir")
	# V8 additive layers on the ground pose (FK deltas, legs' IK untouched):
	# drive (phase-aligned with the gait), brake, and the turn lead
	bt.add_node("a_accel", _anim_node("loco_accel"))
	bt.add_node("accel_seek", _seek_node())
	bt.connect_node("accel_seek", 0, "a_accel")
	bt.add_node("accel_add", AnimationNodeAdd2.new())
	bt.connect_node("accel_add", 0, "turn")
	bt.connect_node("accel_add", 1, "accel_seek")
	bt.add_node("a_brake", _anim_node("loco_brake"))
	bt.add_node("brake_add", AnimationNodeAdd2.new())
	bt.connect_node("brake_add", 0, "accel_add")
	bt.connect_node("brake_add", 1, "a_brake")
	var lead := AnimationNodeBlendSpace1D.new()
	lead.min_space = -1.0
	lead.max_space = 1.0
	lead.add_blend_point(_anim_node("lead_r"), -1.0, -1, "r")
	lead.add_blend_point(_anim_node("add_zero"), 0.0, -1, "zero")
	lead.add_blend_point(_anim_node("lead_l"), 1.0, -1, "l")
	bt.add_node("lead_bs", lead)
	bt.add_node("lead_add", AnimationNodeAdd2.new())
	bt.connect_node("lead_add", 0, "brake_add")
	bt.connect_node("lead_add", 1, "lead_bs")
	# --- air: vertical-velocity blend space
	var air := AnimationNodeBlendSpace1D.new()
	air.min_space = -9.0
	air.max_space = 9.0
	for k in AIR_POINTS:
		air.add_blend_point(_anim_node(k), AIR_POINTS[k], -1, k)
	bt.add_node("air", air)
	# --- splash: impact clip seeked to the authoritative time in the water
	var sk := AnimationNodeTransition.new()
	sk.xfade_time = 0.0
	for i in IMPACTS.size():
		sk.add_input(str(i))
		bt.add_node("a_" + IMPACTS[i], _anim_node(IMPACTS[i]))
	bt.add_node("splash_kind", sk)
	for i in IMPACTS.size():
		bt.connect_node("splash_kind", i, "a_" + IMPACTS[i])
	bt.add_node("splash_seek", _seek_node())
	bt.connect_node("splash_seek", 0, "splash_kind")
	# --- cart
	var cart := AnimationNodeBlendSpace1D.new()
	cart.min_space = -1.0
	cart.max_space = 1.0
	cart.sync = true
	# sim steer +1 = turning right
	cart.add_blend_point(_anim_node("cart_steer_l"), -1.0, -1, "steer_l")
	cart.add_blend_point(_anim_node("cart_drive"), 0.0, -1, "drive")
	cart.add_blend_point(_anim_node("cart_steer_r"), 1.0, -1, "steer_r")
	bt.add_node("cart_bs", cart)
	# --- state machine (as a Transition)
	var st := AnimationNodeTransition.new()
	st.xfade_time = 0.12
	# only restart_emote() requests the current state again: an emote chosen
	# twice restarts (the per-frame _set_mode never re-requests a state)
	st.allow_transition_to_self = true
	var i := 0
	for s in STATES:
		st.add_input(s)
		st.set_input_reset(i, s != "ground")
		i += 1
		if s in ["ground", "air", "splash", "cart"]:
			continue
		bt.add_node("a_" + s, _anim_node(s))
	bt.add_node("state", st)
	i = 0
	for s in STATES:
		match s:
			"ground": bt.connect_node("state", i, "lead_add")
			"air": bt.connect_node("state", i, "air")
			"splash": bt.connect_node("state", i, "splash_seek")
			"cart": bt.connect_node("state", i, "cart_bs")
			_: bt.connect_node("state", i, "a_" + s)
		i += 1
	# --- upper-body action layer: tag wind-up / recovery over running legs
	var ap := AnimationNodeTransition.new()
	ap.xfade_time = 0.0
	for k in ACTS.size():
		ap.add_input(ACTS[k])
		ap.set_input_reset(k, true)
		bt.add_node("act_" + ACTS[k], _anim_node(ACTS[k]))
	bt.add_node("act_pick", ap)
	for k in ACTS.size():
		bt.connect_node("act_pick", k, "act_" + ACTS[k])
	var act := AnimationNodeBlend2.new()
	_filtered(act)
	bt.add_node("act", act)
	bt.connect_node("act", 0, "state")
	bt.connect_node("act", 1, "act_pick")
	# --- overlays
	var fid := AnimationNodeTransition.new()
	fid.xfade_time = 0.0
	for f in FIDGETS:
		fid.add_input(f)
		bt.add_node("a_" + f, _anim_node(f))
	bt.add_node("fidget_pick", fid)
	for k in FIDGETS.size():
		bt.connect_node("fidget_pick", k, "a_" + FIDGETS[k])
	var fidget := AnimationNodeOneShot.new()
	fidget.fadein_time = 0.45
	fidget.fadeout_time = 0.5
	bt.add_node("fidget", fidget)
	bt.connect_node("fidget", 0, "act")
	bt.connect_node("fidget", 1, "fidget_pick")
	var prev := "fidget"
	for variant in ["f", "u"]:
		var mix := AnimationNodeBlend2.new()
		bt.add_node("land_mix_" + variant, mix)
		bt.add_node("a_land_soft_" + variant, _anim_node("land_soft"))
		bt.add_node("a_land_hard_" + variant, _anim_node("land_hard"))
		bt.connect_node("land_mix_" + variant, 0, "a_land_soft_" + variant)
		bt.connect_node("land_mix_" + variant, 1, "a_land_hard_" + variant)
		var os := AnimationNodeOneShot.new()
		os.fadein_time = 0.03
		os.fadeout_time = 0.16
		if variant == "u":
			_filtered(os)
		bt.add_node("land_" + variant, os)
		bt.connect_node("land_" + variant, 0, prev)
		bt.connect_node("land_" + variant, 1, "land_mix_" + variant)
		prev = "land_" + variant
	var rec := AnimationNodeOneShot.new()
	rec.fadein_time = 0.06
	rec.fadeout_time = 0.2
	_filtered(rec)
	bt.add_node("a_recover", _anim_node("recover"))
	bt.add_node("recover", rec)
	bt.connect_node("recover", 0, prev)
	bt.connect_node("recover", 1, "a_recover")
	bt.connect_node("output", 0, "recover")
	tree = AnimationTree.new()
	tree.name = "AnimTree"
	tree.tree_root = bt
	model.add_child(tree)
	tree.anim_player = tree.get_path_to(anim)
	tree.root_node = tree.get_path_to(anim.get_node(anim.root_node))
	tree.callback_mode_process = AnimationMixer.ANIMATION_CALLBACK_MODE_PROCESS_MANUAL
	tree.active = true
	# every state change is a pose fade (CharacterPoseFade); the transition
	# node itself switches at once
	st.xfade_time = 0.0
	_mode = ""
	_set_mode("ground", true)


func _build_effects() -> void:
	PropKit.init_meshes()
	dizzy = Node3D.new()
	dizzy.position = Vector3(0, 1.75, 0)
	add_child(dizzy)
	for k in 3:
		var a := TAU * float(k) / 3.0
		var s := MeshInstance3D.new()
		s.mesh = PropKit.sphere
		s.material_override = PropKit.mat(Color(1.0, 0.86, 0.35), 0.0, Color.WHITE, 1.2)
		s.position = Vector3(cos(a) * 0.32, 0, sin(a) * 0.32)
		s.scale = Vector3.ONE * 0.09
		s.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		dizzy.add_child(s)
	dizzy.visible = false
	bubble = MeshInstance3D.new()
	bubble.mesh = PropKit.sphere
	var bmat := StandardMaterial3D.new()
	bmat.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	bmat.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	bmat.albedo_color = Color(0.44, 0.85, 0.8, 0.14)
	bmat.cull_mode = BaseMaterial3D.CULL_BACK
	bubble.material_override = bmat
	bubble.scale = Vector3(1.4, 1.9, 1.4)
	bubble.position = Vector3(0, 0.85, 0)
	bubble.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	bubble.visible = false
	add_child(bubble)


## V8: the caller hides a view it has nothing to show for (an opponent out
## of this client's interest set, a finished runner); hidden, it does no work.
## Showing it again is a discontinuity: the caller passes snap to apply_state.
func hide_view() -> void:
	visible = false
	if drips:
		drips.emitting = false


## The ground height under a foot (world y), or NAN: a short ray against
## the static world (never characters, carts or water).
func _probe_ground(p: Vector3) -> float:
	if ground_fn.is_valid():
		return ground_fn.call(p)
	var space := get_world_3d().direct_space_state
	if space == null:
		return NAN
	var q := PhysicsRayQueryParameters3D.create(p + Vector3(0, 0.4, 0), p - Vector3(0, 0.4, 0), TC.L_WORLD)
	var hit := space.intersect_ray(q)
	return float((hit["position"] as Vector3).y) if not hit.is_empty() else NAN


## Loading time (V8): effect nodes this character will need, made now.
func prewarm_fx() -> void:
	_ensure_drips()


func _ensure_drips() -> void:
	if drips != null:
		return
	drips = Fx.make_drip_emitter()
	drips.position = Vector3(0, 0.9, 0)
	drips.visible = false
	add_child(drips)


func _build_flashlight() -> void:
	if flashlight != null:
		return
	var hand := skeleton.find_bone("hand.R")
	var att := BoneAttachment3D.new()
	att.bone_name = "hand.R"
	skeleton.add_child(att)
	# the flashlight mesh is built pointing along the model's forward (-Z)
	# at rest; keep the light aligned with it relative to the hand bone
	var lens_rest := Transform3D(Basis(), Vector3(0.409, 0.555, -0.105))
	var bone_rest := skeleton.get_bone_global_rest(hand)
	var holder := Node3D.new()
	holder.transform = bone_rest.affine_inverse() * lens_rest
	att.add_child(holder)
	flashlight = SpotLight3D.new()
	flashlight.light_color = Color(1.0, 0.95, 0.82)
	flashlight.light_energy = 2.6
	flashlight.spot_range = 20.0
	flashlight.spot_angle = 22.0
	flashlight.spot_attenuation = 0.9
	flashlight.shadow_enabled = false
	holder.add_child(flashlight)
	beam = MeshInstance3D.new()
	var bm := CylinderMesh.new()
	bm.top_radius = 0.05
	bm.bottom_radius = 2.4
	bm.height = 9.0
	bm.radial_segments = 16
	bm.cap_top = false
	bm.cap_bottom = false
	beam.mesh = bm
	var gm := ShaderMaterial.new()
	gm.shader = preload("res://assets/shaders/glow_add.gdshader")
	gm.set_shader_parameter("color", Color(1.0, 0.92, 0.72))
	gm.set_shader_parameter("intensity", 0.1)
	gm.set_shader_parameter("mode", 2.0)
	beam.material_override = gm
	beam.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	# CylinderMesh top (UV.y = 0, brightest in glow_add) sits at the lens
	beam.position = Vector3(0, 0, -4.6)
	beam.rotation = Vector3(PI * 0.5, 0, 0)
	holder.add_child(beam)


func _label_color() -> Color:
	return Color("ffc668") if role == TC.Role.PATROL else Color("f4f2ec")


func _build_label(display_name: String, is_bot: bool) -> void:
	if name_label == null:
		name_label = Label3D.new()
		add_child(name_label)
	# names are plain text (Label3D has no markup), already validated upstream
	name_label.text = (display_name + "  ·  BOT") if is_bot else display_name
	name_label.font = UIKit.font(true)
	name_label.font_size = 30
	name_label.outline_size = 10
	name_label.pixel_size = 0.0011
	name_label.billboard = BaseMaterial3D.BILLBOARD_ENABLED
	name_label.no_depth_test = false
	name_label.fixed_size = true
	name_label.position = Vector3(0, 2.05, 0)
	name_label.modulate = _label_color()
	name_label.outline_modulate = Color("11192b")
	# bots' tags only up close (less clutter); players' further out
	name_label.visibility_range_end = 14.0 if is_bot else 30.0
	name_label.visibility_range_end_margin = 4.0 if is_bot else 8.0
	# right next to the camera the label would float high over the HUD, and
	# the player is plainly visible anyway
	name_label.visibility_range_begin = 3.5
	name_label.visibility_range_begin_margin = 1.0
	name_label.visibility_range_fade_mode = GeometryInstance3D.VISIBILITY_RANGE_FADE_SELF
	name_label.visible = not is_local and display_name != ""


func _apply_cosmetics() -> void:
	var patrol := role == TC.Role.PATROL
	var want: Array = []
	if patrol:
		want = ["base", "watch", "flashlight"]
		want.append_array(Cosmetics.entry("marks", cosmetic["marks"])["parts"])
		if int(Cosmetics.entry("color", cosmetic["color"])["id"]) % 2 == 1:
			want.append("mustache")
	else:
		# (V5: under a crown or headphones the curly crop is its smooth-band
		# variant; V6 moved that rule into Cosmetics.runner_parts with the
		# new hats and the outfits' own headwear)
		want = Cosmetics.runner_parts(cosmetic)
	visible_parts.clear()
	for n in parts:
		var mi: MeshInstance3D = parts[n]
		mi.visible = n in want
		if mi.visible:
			visible_parts.append(mi)
	var t: Array = Cosmetics.tints(cosmetic)
	var stripes := 0.0 if patrol else Cosmetics.stripes_per_m(cosmetic)
	var rim := Color(1.0, 0.78, 0.55) if lighting == "indoor" else Color(0.55, 0.68, 1.0)
	for mi in visible_parts:
		mi.set_instance_shader_parameter("tint_primary", t[0])
		mi.set_instance_shader_parameter("tint_secondary", t[1])
		mi.set_instance_shader_parameter("tint_dark", t[2])
		# (Pass 9: a complete skin's own tones; the Night Watch the player's)
		mi.set_instance_shader_parameter("tint_skin", Cosmetics.skin_color(cosmetic) if patrol else Cosmetics.look_skin_color(cosmetic))
		mi.set_instance_shader_parameter("tint_hair", Cosmetics.hair_color(cosmetic) if patrol else Cosmetics.look_hair_color(cosmetic))
		mi.set_instance_shader_parameter("stripes", stripes)
		mi.set_instance_shader_parameter("rim_color", rim)
		mi.set_instance_shader_parameter("rim_strength", 0.14 if lighting == "indoor" else 0.1)
		mi.set_instance_shader_parameter("wet", _wet)
		mi.set_instance_shader_parameter("skin_warm", 0.03 if lighting == "indoor" else 0.15)
	_face_base = Cosmetics.face_keys(cosmetic) if patrol else Cosmetics.look_face_keys(cosmetic)
	_bind_face("base" if patrol else Cosmetics.head_part(cosmetic))
	# nightcap tip spring only when it is worn
	var cap := not patrol and "hat_nightcap" in want
	if cap and hat_spring == null:
		hat_spring = SpringBoneSimulator3D.new()
		skeleton.add_child(hat_spring)
		hat_spring.setting_count = 1
		# only the tip swings: with the chain rooted at hat1 the wide middle
		# of the cap sagged into the head and the scalp showed through it
		hat_spring.set_root_bone_name(0, "hat2")
		hat_spring.set_end_bone_name(0, "hat3")
		hat_spring.set_extend_end_bone(0, true)
		hat_spring.set_end_bone_length(0, 0.1)
		hat_spring.set_gravity(0, 0.2)
		hat_spring.set_radius(0, 0.03)
		# V5: simulate in the character's own space.  In world space a 250 ms
		# hitch or a landing flung the tip 30-40 cm in one frame; inertia now
		# comes from the filtered body acceleration (external_force, below).
		hat_spring.set_center_from(0, SpringBoneSimulator3D.CENTER_FROM_NODE)
		hat_spring.set_center_node(0, hat_spring.get_path_to(self))
		# keep the tip out of the head (a sphere just inside the head shell)
		var head_col := SpringBoneCollisionSphere3D.new()
		head_col.bone_name = "head"
		head_col.position_offset = Vector3(0.0, 0.255, 0.0)
		head_col.radius = 0.25
		hat_spring.add_child(head_col)
		_apply_hat_tuning()
	if hat_spring:
		hat_spring.active = cap
	if patrol:
		_build_flashlight()
	if flashlight:
		flashlight.get_parent().visible = patrol


## Pass 9: expressions and face presets play on the head that is shown (a
## complete skin has its own, with the same shape names).  The newly shown
## head starts from the current expression, so a swap never shows a frame of
## a neutral face; the hidden head is left as it was.
func _bind_face(part: String) -> void:
	var name_ := part if _face_idx_of.has(part) else "base"
	face_mesh = parts[name_]
	_face_idx = _face_idx_of[name_]
	for key in _face:
		if _face_idx.has(key):
			face_mesh.set_blend_shape_value(_face_idx[key], minf(1.0, float(_face[key]) + float(_face_base.get(key, 0.0))))


## Show a still face on the visible head: the held face keys plus `extra`
## (portraits and dev captures; play-time faces come from _update_face).
func show_face(extra: Dictionary = {}) -> void:
	for key in _face_idx:
		var w := float(_face_base.get(key, 0.0)) + float(extra.get(key, 0.0))
		face_mesh.set_blend_shape_value(_face_idx[key], clampf(w, 0.0, 1.0))


## Nightcap tip spring: lively in play, calm and better damped in menus.
func _apply_hat_tuning() -> void:
	if hat_spring == null:
		return
	hat_spring.set_stiffness(0, 2.6 if menu_idle else 1.8)
	hat_spring.set_drag(0, 0.7 if menu_idle else 0.45)


func set_flash(v: float, col: Color = Color.WHITE) -> void:
	for mi in visible_parts:
		mi.set_instance_shader_parameter("flash", v)
		mi.set_instance_shader_parameter("flash_color", col)


func _set_wet(v: float) -> void:
	if absf(v - _wet) < 0.01 and v > 0.0:
		return
	_wet = v
	for mi in visible_parts:
		mi.set_instance_shader_parameter("wet", v)


## Turn to look at a point (menus/lobby): yaw such that -Z points at `p`.
func face_toward(p: Vector3) -> void:
	var d := p - global_position
	rotation.y = atan2(-d.x, -d.z)
	_vis_yaw = rotation.y
	_have_yaw = true


## Set the facing directly (menus: placement, creator turntable), no easing.
func set_facing(yaw: float) -> void:
	rotation.y = yaw
	_vis_yaw = yaw
	_have_yaw = true
	rs["yaw"] = yaw


## Lobby departure: a wave, then shrink away and free (Reduced Motion: quick).
func play_leave() -> void:
	set_process(true)
	rs["emote"] = 0
	rs["emote_t"] = 1.0
	var tw := create_tween()
	tw.tween_interval(0.15 if reduced_motion else 0.7)
	tw.tween_property(self, "scale", Vector3.ONE * 0.01, 0.12 if reduced_motion else 0.25).set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_IN)
	tw.tween_callback(queue_free)


## One brief arrival hop (lobby).
func play_arrive() -> void:
	_arrive_t = 0.9


## Ready-up response (lobby).
func play_ready() -> void:
	_ready_t = 0.9


## A deliberate action (emote, move preview) takes over from the automatic
## arrival / ready responses.
func cancel_reactions() -> void:
	_ready_t = 0.0
	_arrive_t = 0.0


## Restart an emote that is already playing (choosing the same emote again
## plays it from the start; the state input resets on a self-transition).
func restart_emote(id: int) -> void:
	if tree == null or id < 0 or id >= TC.EMOTES.size():
		return
	var m := "emote_" + String(TC.EMOTES[id])
	if _mode == m:
		_fade_from_shown(0.15)
		tree.set("parameters/state/transition_request", m)
		_mode_t = 0.0


## The host said this Night Watch's lunge found nobody (TAG_MISS event).
func tag_missed() -> void:
	_miss_t = 0.5


## Hard reset of presentation history (respawn, teleport, cart entry/exit,
## reconnect, spectator switch): no lag/spring carries across the jump.
func reset_motion() -> void:
	_have_prev = false
	_have_yaw = false
	_prev_vel = Vector3.ZERO
	_squash = 0.0
	_squash_v = 0.0
	_travel_f = Vector3.ZERO
	_have_last = false
	_fwd_acc_f = 0.0
	if secondary:
		secondary.reset_motion()
	if foot_lock:
		foot_lock.reset()
	if hat_spring:
		hat_spring.reset()
		hat_spring.external_force = Vector3.ZERO


## rs keys: pos, yaw, vel, state, state_t, on_floor, diving, fast,
## tag_phase, protect, bump_protect, spotted, cart_id, steer, emote, emote_t,
## celebrate, visible, impact.  The caller supplies render-time
## values (already interpolated); this view does not smooth position again.
## snap: the caller saw a discontinuity (respawn, resurfacing, cart seat,
## reconnect, a big correction).  Histories reset when the character really
## moved; a move of more than CUT_DIST also cuts the pose (no fade across a
## teleport).
func apply_state(state_rs: Dictionary, _delta: float = 0.0, snap: bool = false) -> void:
	rs = state_rs
	var before := global_position
	if rs.has("pos"):
		global_position = rs["pos"]
	if snap and (before.distance_to(global_position) > 0.05 or not _have_prev):
		reset_motion()
		if before.distance_to(global_position) > CUT_DIST:
			_cut = true
	if rs.has("yaw") and (snap or not _have_yaw):
		_vis_yaw = float(rs["yaw"])
		rotation.y = _vis_yaw
		_have_yaw = true


## Change the animation state.  The change fades from the pose on screen
## (CharacterPoseFade) over the state's time, or cuts (teleports).
func _set_mode(m: String, cut: bool = false) -> void:
	if m == _mode or tree == null:
		return
	var x: float = STATES.get(m, 0.12)
	# out of an emote, celebration or lobby reaction: a calmer settle
	if m == "ground" and (_mode.begins_with("emote_") or _mode in ["celebrate", "ready", "arrive"]):
		x = 0.28
	x *= 0.5 if reduced_motion else 1.0
	if cut:
		if pose_fade:
			pose_fade.cut()
		x = 0.0
	else:
		_fade_from_shown(x)
	tree.set("parameters/state/transition_request", m)
	if _fidget_on:
		tree.set("parameters/fidget/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FADE_OUT)
		_fidget_on = false
	_mode = m
	_mode_t = 0.0


## Start a pose fade from what is on screen (not for throttled distant
## characters, whose 20 Hz pose has no useful velocity: they switch at once).
func _fade_from_shown(x: float) -> void:
	if pose_fade == null:
		return
	if _far and not is_local:
		pose_fade.cut()
	else:
		pose_fade.capture(x)


## Teleport: no fade, no overlay carried across, histories already reset.
func _cut_pose() -> void:
	_cut = false
	if pose_fade:
		pose_fade.cut()
	for os in ["land_f", "land_u", "fidget", "turn", "stop"]:
		tree.set("parameters/%s/request" % os, AnimationNodeOneShot.ONE_SHOT_REQUEST_ABORT)
	_stop_on = false
	_fidget_on = false
	_act_w = 0.0
	tree.set("parameters/act/blend_amount", 0.0)


## Visual facing: follows the sim yaw closely but never snaps (aim-assist
## turns, snapshot gaps) and never spins the long way back during a reversal.
## V5: in plain ground locomotion the sim is turning its yaw toward the
## velocity at a capped rate (turn_rate_deg); the drawn body aims at the
## heading of its actual ground travel directly, so it does not run sideways
## for the ~0.2 s of a turn or reversal (planted feet skated at 5-7 m/s
## there).  Tag phases, dives, other states and runs on the spot (lobby
## previews) keep the sim's facing.
func _update_yaw(delta: float) -> float:
	var target := float(rs.get("yaw", rotation.y))
	# heading of the filtered ground travel (prediction corrections jitter the
	# raw velocity; a run on the spot in the lobby travels nowhere)
	var hv := Vector2(_travel_f.x, _travel_f.z)
	if _mode == "ground" and int(rs.get("tag_phase", 0)) == 0 and not bool(rs.get("diving", false)) \
			and int(rs.get("state", TC.PState.ACTIVE)) == TC.PState.ACTIVE and hv.length() > 0.8:
		var heading := atan2(-hv.x, -hv.y)
		target += wrapf(heading - target, -PI, PI) * smoothstep(0.8, 2.0, hv.length())
	if not _have_yaw:
		_vis_yaw = target
		_have_yaw = true
		_turn_sign = 0.0
		return 0.0
	var d := wrapf(target - _vis_yaw, -PI, PI)
	# around 180 degrees the shortest way can flip sides from frame to frame:
	# keep turning the way the turn started
	if absf(d) > 2.7 and _turn_sign != 0.0 and signf(d) != _turn_sign:
		d += TAU * _turn_sign
	if absf(d) > 0.05:
		_turn_sign = signf(d)
	elif absf(d) < 0.01:
		_turn_sign = 0.0
	var step := d * (1.0 - exp(-delta * 24.0))
	_vis_yaw = wrapf(_vis_yaw + step, -PI, PI)
	rotation.y = _vis_yaw
	return step


func _process(delta: float) -> void:
	# V8: visibility has one owner, the caller (MatchController.view_shown);
	# a hidden view does no animation or effects work
	if not visible:
		return
	if not Prof.on:
		_process_view(delta)
		return
	var t0 := Prof.t()
	_process_view(delta)
	Prof.add("views", t0)
	Prof.count("views_processed")


func _process_view(delta: float) -> void:
	if model == null or rs.is_empty():
		return
	_t += delta
	_mode_t += delta
	var st: int = rs.get("state", TC.PState.ACTIVE)
	var vel: Vector3 = rs.get("vel", Vector3.ZERO)
	var speed := Vector2(vel.x, vel.z).length()
	var on_floor: bool = rs.get("on_floor", true)
	var diving: bool = rs.get("diving", false)
	# Pass 9: "fast" = at or near full speed (the render state's "sprinting"
	# until then; there is no sprint any more)
	var sprinting: bool = rs.get("fast", rs.get("sprinting", false))
	var tag_phase: int = rs.get("tag_phase", 0)
	var state_t: float = rs.get("state_t", 0.0)
	var finished := st == TC.PState.FINISHED
	var captured := st == TC.PState.CAPTURED
	var emote: int = rs.get("emote", -1)
	var emote_t: float = rs.get("emote_t", 0.0)
	# camera distance once per frame (LOD with hysteresis, sounds, effects)
	_cam_d = _camera_distance()
	_far = _cam_d > (LOD_NEAR if _far else LOD_FAR)
	if pose_fade:
		pose_fade.tracking = is_local or not _far

	# --- teleports: a state change that moved the character (respawn after
	# capture, resurfacing at a shore exit, cart seat in/out) resets motion
	# history and cuts the pose; any other state change fades (_set_mode)
	var entered_splash := false
	if st != _prev_state and _prev_state >= 0:
		if global_position.distance_to(_last_pos) > CUT_DIST:
			reset_motion()
			_cut = true
			_vis_yaw = float(rs.get("yaw", rotation.y))
			rotation.y = _vis_yaw
			_have_yaw = true
		if _prev_state == TC.PState.SPLASHING and st == TC.PState.ACTIVE:
			_on_resurface()
	if st == TC.PState.SPLASHING and _prev_state != TC.PState.SPLASHING:
		entered_splash = true
	_prev_state = st
	# the character's actual ground travel (filtered): a run on the spot (the
	# lobby's "Try moves") has a velocity but no travel
	# (no previous position yet - the first frame, or after a reset - is
	# not travel: a view placed away from the origin would otherwise start
	# facing along the line from the origin and swing back)
	# V8: travel is measured without the caller's presentation correction
	# (rs "corr": the local player's decaying reconcile offset), which is not
	# movement: a sideways correction turned the body and nudged cadence
	var base := global_position - (rs.get("corr", Vector3.ZERO) as Vector3)
	if delta > 0.0 and not _cut and _have_last:
		var travel := (base - _last_base) / delta
		_travel_f += (Vector3(travel.x, 0.0, travel.z) - _travel_f) * (1.0 - exp(-delta / ACC_TAU))
	else:
		_travel_f = Vector3.ZERO
	_last_pos = global_position
	_last_base = base
	_have_last = true

	# --- facing + motion history.  Acceleration is the derivative of a
	# filtered velocity: bounded by (velocity change) / ACC_TAU whatever the
	# render delta, so a tick or snapshot landing in a 4 ms frame, a hitch or
	# a prediction correction no longer kicks the springs.
	var yaw_step := _update_yaw(delta)
	var accel := Vector3.ZERO
	var yaw_rate := 0.0
	if _have_prev and delta > 0.0:
		var nf := _vel_f + (vel - _vel_f) * (1.0 - exp(-delta / ACC_TAU))
		accel = ((nf - _vel_f) / delta).limit_length(ACC_MAX)
		_vel_f = nf
		yaw_rate = yaw_step / delta
	else:
		_vel_f = vel
	_prev_vel = vel
	_have_prev = true
	var accel_local := global_transform.basis.inverse() * accel
	_fwd_acc = -accel_local.z
	# the layers read a slower, dead-zoned acceleration: a reconcile's
	# velocity noise (a few m/s^2, alternating) is not a start or a brake
	_fwd_acc_f += (_fwd_acc - _fwd_acc_f) * (1.0 - exp(-maxf(delta, 0.0) / 0.1))
	var calm := 0.6 if menu_idle else 1.0
	if secondary:
		secondary.accel = accel_local
		secondary.turn_rate = yaw_rate
		secondary.speed = speed
		secondary.gain = (0.4 if reduced_motion else 1.0) * calm
	if hat_spring and hat_spring.active:
		hat_spring.external_force = (-accel_local * HAT_INERTIA * calm * (0.5 if reduced_motion else 1.0)).limit_length(HAT_FORCE_MAX)

	# --- landing / jump / dive edges (sounds + squash), debounced so a
	# prediction correction that flickers on_floor never doubles a sound
	var air := not on_floor and st == TC.PState.ACTIVE
	_since_land += delta
	_since_jump += delta
	if air:
		_air_t += delta
		_fall_speed = maxf(_fall_speed, -vel.y)
	_air_hold = _air_hold + delta if air else 0.0
	# the air pose shows for a real jump at once, otherwise only after
	# AIR_DEBOUNCE off the floor (kerbs, crests and contact flicker)
	_air_vis = air and (vel.y > 1.0 or diving or _air_hold >= AIR_DEBOUNCE)
	if _prev_air and not air and st == TC.PState.ACTIVE:
		if _prev_diving or diving:
			_dive_land_t = DIVE_LAND_S
		elif _fall_speed > 2.5 and _air_t > 0.12 and _since_land > 0.25:
			_land(_fall_speed, speed)
		_fall_speed = 0.0
		_air_t = 0.0
	if not _prev_air and air and vel.y > 2.0 and st == TC.PState.ACTIVE and _since_jump > 0.3:
		_since_jump = 0.0
		_squash_v = -1.5
		if _near_camera(25.0):
			Sfx.play("jump", global_position, -6.0)
	if not air:
		_air_t = 0.0
	if diving and not _prev_diving and _near_camera(25.0):
		Sfx.play("dive", global_position, -4.0)
	_prev_air = air
	_prev_diving = diving
	_dive_land_t = maxf(0.0, _dive_land_t - delta)
	_arrive_t = maxf(0.0, _arrive_t - delta)
	_ready_t = maxf(0.0, _ready_t - delta)
	_miss_t = maxf(0.0, _miss_t - delta)
	_turn_cd = maxf(0.0, _turn_cd - delta)

	# --- choose the animation state (+ the upper-body action layer)
	var m := "ground"
	var act := ""
	if st == TC.PState.ENTERING:
		m = "cart_enter"
	elif st == TC.PState.IN_CART:
		m = "cart"
	elif st == TC.PState.EXITING:
		m = "cart_exit"
	elif captured:
		m = "flop" if state_t < 0.9 else "dizzy"
	elif st == TC.PState.SPLASHING:
		m = "splash"
	elif st == TC.PState.STUMBLE:
		m = "stumble"
	elif finished or bool(rs.get("celebrate", false)):
		m = "celebrate"
	elif diving:
		m = "dive"
	elif _dive_land_t > 0.0:
		m = "dive_land"
	elif tag_phase == 2:
		m = "tag_lunge"
	elif tag_phase == 1 or tag_phase == 3:
		var clip := "tag_windup" if tag_phase == 1 else ("tag_miss" if _miss_t > 0.0 else "tag_recover")
		if speed > ACT_RUN_SPEED or _air_vis:
			# moving: the legs keep running, the arms and torso tag
			act = clip
			m = "air" if _air_vis else "ground"
		else:
			m = clip
	elif _air_vis:
		m = "air"
	elif emote >= 0 and emote_t > 0.0 and speed < 1.0:
		m = "emote_" + TC.EMOTES[emote]
	elif _ready_t > 0.0:
		m = "ready"
	elif _arrive_t > 0.0:
		m = "arrive"
	var cut_now := _cut
	if _cut:
		_cut_pose()
		_set_mode(m, true)
		_move_w = smoothstep(0.15, 0.9, speed)
		_bs = clampf(speed, LOCO_POINTS["walk"], LOCO_POINTS["sprint"])
		_settle_to = -1.0
	else:
		_set_mode(m)
	_update_act(act, delta)

	# --- per-state parameters
	_idle_clock += delta * (0.8 if menu_idle else 1.0)
	tree.set("parameters/idle_seek/seek_request", fmod(_idle_clock, IDLE_LEN))
	if m == "ground":
		_update_ground(delta, vel, speed, on_floor, sprinting, yaw_rate)
	else:
		_clear_layers()
		_still_t = 0.0
		tree.set("parameters/loco_seek/seek_request", fposmod(_phase, 1.0))
		if foot_lock:
			foot_lock.weight = 0.0
	if m == "air":
		tree.set("parameters/air/blend_position", clampf(vel.y, AIR_POINTS["air_fall"], AIR_POINTS["air_rise"]))
	elif m == "cart":
		tree.set("parameters/cart_bs/blend_position", clampf(float(rs.get("steer", 0.0)), -1.0, 1.0))
	if st == TC.PState.SPLASHING:
		_update_splash(delta, state_t, entered_splash)
	else:
		_splash_t = -1.0

	# --- squash & stretch (scale about the feet): a small damped spring
	# kicked by landings and take-offs, so the body never snaps in one frame
	_squash_step(delta)
	var sq := _squash * (0.4 if reduced_motion else 1.0)
	model.scale = Vector3(1.0 + sq * 0.5, 1.0 - sq, 1.0 + sq * 0.5)

	# --- effects
	dizzy.visible = captured and state_t > 0.5 and state_t < 4.5
	if dizzy.visible:
		dizzy.rotation.y += delta * 5.0
	bubble.visible = float(rs.get("protect", 0.0)) > 0.0 and not captured
	if bubble.visible:
		(bubble.material_override as StandardMaterial3D).albedo_color.a = 0.10 + 0.06 * sin(_t * 10.0)
	if flashlight:
		var show_light := role == TC.Role.PATROL and m != "cart" and m != "cart_enter"
		flashlight.visible = show_light
		beam.visible = show_light
	var flash := 0.0
	if float(rs.get("protect", 0.0)) > 0.0:
		flash = 0.18 + 0.14 * sin(_t * 16.0)
	elif float(rs.get("bump_protect", 0.0)) > 0.0:
		flash = 0.15
	set_flash(flash, Color("6fd8cc"))
	if _wet > 0.0 and st != TC.PState.SPLASHING:
		_set_wet(maxf(0.0, _wet - delta / 5.0))
	if drips:
		_drip_t = maxf(0.0, _drip_t - delta)
		drips.emitting = _drip_t > 0.0 and visible
		# shown only while it drips and its last drops fall (an idle emitter
		# is still a rendered object and a draw call)
		_drip_show_t = drips.lifetime + 0.1 if drips.emitting else maxf(0.0, _drip_show_t - delta)
		drips.visible = _drip_show_t > 0.0

	# --- schedule (V8): distant characters animate on an elapsed-time clock,
	# FAR_ANIM_STEP apart at any frame rate (V5-V7 counted rendered frames:
	# every third frame was 20 Hz at 60 fps but 10 Hz at 30), staggered per
	# slot so they don't all advance on the same frame
	var far := _far and not is_local
	var due := true
	if far and not cut_now:
		_far_clock += delta
		due = _far_clock >= FAR_ANIM_STEP
		if due:
			_far_clock = minf(_far_clock - FAR_ANIM_STEP, FAR_ANIM_STEP)
	else:
		_far_clock = _far_stagger * FAR_ANIM_STEP
	# --- face (distant characters: at their animation rate)
	_face_acc += delta
	if due:
		_update_face(_face_acc, m, sprinting, tag_phase, bool(rs.get("spotted", false)))
		_face_acc = 0.0

	# --- animate (manual advance: distant characters update at a lower rate,
	# with the real elapsed time accumulated so they keep the right pace)
	if not tree.active:
		return
	_anim_acc += delta
	if due:
		var ta := Prof.t()
		tree.advance(_anim_acc)
		Prof.add("anim_advance", ta)
		Prof.count("anim_advances")
		anim_time_advanced += _anim_acc
		_anim_acc = 0.0
	if hat_spring and _hat_off:
		_hat_off = false
		hat_spring.active = true
		hat_spring.reset()
	if cut_now and hat_spring and hat_spring.active:
		# teleport: the cap shows its rest shape in the cut frame and the
		# spring restarts from there next frame (a reset alone settled one
		# frame late: a second 22 cm jump after the cut)
		hat_spring.active = false
		_hat_off = true


## Upper-body action layer (tag wind-up / recovery while moving).
func _update_act(act: String, delta: float) -> void:
	if act != "" and act != _act:
		# the action starts at once, from the pose on screen (a weight ramp
		# over the running arms measured as a 26 cm snap at the mitten)
		_fade_from_shown(0.1)
		tree.set("parameters/act_pick/transition_request", act)
		_act = act
		_act_w = 1.0
	var want := 1.0 if act != "" else 0.0
	_act_w += (want - _act_w) * (1.0 - exp(-delta / 0.09))
	if want == 0.0 and _act_w < 0.01:
		_act_w = 0.0
		_act = ""
	tree.set("parameters/act/blend_amount", _act_w)


const SQ_OMEGA := 20.0
const SQ_ZETA := 0.5


func _squash_step(delta: float) -> void:
	var t := minf(delta, 0.1)
	while t > 0.0:
		var h := minf(t, 1.0 / 120.0)
		var a := -_squash * SQ_OMEGA * SQ_OMEGA - _squash_v * 2.0 * SQ_ZETA * SQ_OMEGA
		_squash_v += a * h
		_squash += _squash_v * h
		t -= h
	_squash = clampf(_squash, -0.08, 0.15)


## V8: the authored transition layers on the ground pose.  Drive: a start
## from a standstill holds the push-off posture for ~0.25 s, and any hard
## forward acceleration shows it, in step with the gait.  Brake: hard
## deceleration from a run sits the body back.  Turn lead: while the body
## turns fast (a sharp turn or a 180), the head and chest lead the turn and
## the hips stay with the gait; the side is chosen when the lead starts and
## kept until it has eased off (~0.25 s after the turn), so a reversal that
## passes through 180 degrees never flips it.  All follow the
## character's real motion (its velocity and facing); none moves the body.
func _update_layers(delta: float, speed: float, want: float, yaw_rate: float) -> void:
	var rm := 0.5 if reduced_motion else 1.0
	# an upper-body action (the Night Watch's tag) owns the torso and arms:
	# the layers yield (the lunge's 9 m/s burst is not a start, its end not a brake)
	var free := 0.0 if (_act != "" or int(rs.get("tag_phase", 0)) != 0) else 1.0
	_run_mem = maxf(speed, _run_mem * exp(-delta / 0.35))
	_start_t += delta
	var run_k := smoothstep(1.5, 3.5, maxf(speed, _bs * _move_w))
	var start_env := 1.0 - smoothstep(0.22, 0.55, _start_t)
	var drive := maxf(start_env, clampf((_fwd_acc_f - ACCEL_DEAD) / (ACCEL_REF - ACCEL_DEAD), 0.0, 1.0)) * run_k * _move_w * free
	_accel_w += (drive - _accel_w) * (1.0 - exp(-delta / (0.04 if drive > _accel_w else 0.12)))
	if _stop_on:
		# the planted stop takes over the lean: hand it off from zero slope
		# (an exponential decay would kick the arms the frame the stop fires)
		_brake_w = _brake_hold * (1.0 - smoothstep(0.0, 0.3, STOP_LEN - _stop_t))
	else:
		var brake := clampf((-_fwd_acc_f - ACCEL_DEAD) / (BRAKE_REF - ACCEL_DEAD), 0.0, 1.0) * smoothstep(1.5, 3.5, _run_mem) * free
		_brake_w += (brake - _brake_w) * (1.0 - exp(-delta / (0.04 if brake > _brake_w else 0.15)))
	if _lead_w < 0.15 and absf(yaw_rate) > 1.5:
		_lead_sign = signf(yaw_rate)
	var lt := smoothstep(2.0, 7.0, absf(yaw_rate)) * smoothstep(1.0, 3.0, speed) * want * free
	if signf(yaw_rate) != _lead_sign:
		lt = 0.0
	_lead_w += (lt - _lead_w) * (1.0 - exp(-delta / (0.05 if lt > _lead_w else 0.25)))
	_lead_pos += (_lead_sign - _lead_pos) * (1.0 - exp(-delta / 0.06))
	if _stop_on:
		_stop_t -= delta
		if _stop_t <= 0.0:
			_stop_on = false
	tree.set("parameters/accel_seek/seek_request", fposmod(_phase, 1.0))
	tree.set("parameters/accel_add/add_amount", _accel_w * rm)
	tree.set("parameters/brake_add/add_amount", _brake_w * rm)
	tree.set("parameters/lead_bs/blend_position", _lead_pos)
	tree.set("parameters/lead_add/add_amount", _lead_w * rm)


## The stop from a run plants: the foot that is coming through at the
## settle point (right at phase 0, left at 0.5) reaches out and takes it.
func _begin_stop() -> void:
	# (not from an action: the Night Watch's lunge burst is not a run, and the
	# miss's recovery stopping the body is not a planted stop)
	if _run_mem < STOP_FROM or _stop_on or (_far and not is_local) or _act != "" or int(rs.get("tag_phase", 0)) != 0:
		return
	var side := "r" if is_zero_approx(fposmod(_settle_to, 1.0)) else "l"
	tree.set("parameters/stop_dir/transition_request", side)
	tree.set("parameters/stop/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)
	_stop_on = true
	_stop_t = STOP_LEN
	_brake_hold = _brake_w
	stat_stops += 1


func _clear_layers() -> void:
	_accel_w = 0.0
	_brake_w = 0.0
	_lead_w = 0.0
	if _stop_on:
		tree.set("parameters/stop/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_ABORT)
		_stop_on = false
	for n in ["accel_add", "brake_add", "lead_add"]:
		tree.set("parameters/%s/add_amount" % n, 0.0)


func _update_ground(delta: float, vel: Vector3, speed: float, on_floor: bool, sprinting: bool, yaw_rate: float) -> void:
	# while the body turns, the gait advances with the forward part of the
	# ground speed (no moonwalk while the facing catches up in a reversal).
	# Without a turn in progress (a run on the spot in the lobby) speed rules.
	var fwd_speed := speed
	var align := 1.0
	var turning := absf(yaw_rate) > 1.5 or absf(wrapf(float(rs.get("yaw", _vis_yaw)) - _vis_yaw, -PI, PI)) > 0.35
	if turning and speed > 0.05:
		var f := Vector3(vel.x, 0.0, vel.z).dot(Vector3(-sin(_vis_yaw), 0.0, -cos(_vis_yaw)))
		align = clampf(f / speed, -1.0, 1.0)
		fwd_speed = speed if align > 0.0 else 0.0
	var want := smoothstep(0.15, 0.9, speed)
	if _move_w < 0.01 and want > 0.0:
		# from a standstill the gait begins on a step: one foot under the body,
		# the other passing it (the loops have those poses at phase 0 and 0.5)
		_phase = roundf(_phase * 2.0) * 0.5
		_step_init = false
		_settle_to = -1.0
		_bs = clampf(speed, LOCO_POINTS["walk"], LOCO_POINTS["sprint"])
		_start_t = 0.0
	if want > 0.3 and _stop_on:
		# moving again before the stop finished: hand back to the gait
		tree.set("parameters/stop/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FADE_OUT)
		_stop_on = false
	# the sim reaches full speed in ~0.1 s: blend the legs in fast, out a
	# little slower, never in one frame
	_move_w += (want - _move_w) * (1.0 - exp(-delta / (0.045 if want > _move_w else 0.085)))
	if want == 0.0 and _move_w < 1e-3:
		_move_w = 0.0
	# blend-space speed follows the ground speed through a very short filter:
	# 0.08 s measured as more foot slide in turns (0.95 vs 0.42 m/s), none
	# let prediction corrections shake the pose.  The cadence uses the
	# stride of the pose shown, so planted feet move at ground speed.
	_bs += (clampf(speed, LOCO_POINTS["walk"], LOCO_POINTS["sprint"]) - _bs) * (1.0 - exp(-delta / BS_TAU))
	var rate := fwd_speed / _m_per_cycle(_bs) if speed > 0.05 else 0.0
	if want < 0.02 and _move_w > 0.02:
		# stopping: finish the step in progress and hold on the next half
		# cycle (one foot planted under the body, the other beside it)
		if _settle_to < 0.0:
			_settle_to = ceilf(_phase * 2.0) * 0.5
			_begin_stop()
		_phase = minf(_phase + delta * maxf(rate, 2.4), _settle_to)
	else:
		_settle_to = -1.0
		_phase += delta * rate
	tree.set("parameters/loco/blend_position", _bs)
	tree.set("parameters/move/blend_amount", _move_w)
	tree.set("parameters/loco_seek/seek_request", fposmod(_phase, 1.0))
	_update_layers(delta, speed, want, yaw_rate)
	# V6 foot lock: on for ground locomotion that really travels (not a run
	# on the spot in the lobby, not a throttled distant character)
	if foot_lock:
		# "on the spot" only when it lasts (a reversal passes through zero
		# travel for a moment and keeps the lock)
		var travel := Vector2(_travel_f.x, _travel_f.z).length()
		_spot_t = _spot_t + delta if speed > 0.5 and travel < speed * 0.3 else 0.0
		var on_spot := _spot_t > 0.25
		foot_lock.weight = _move_w if on_floor and not on_spot and _act == "" and not (_far and not is_local) else 0.0
		# V8 terrain contact: nearby characters in a match sample the ground
		# under each foot at touch-down (one ray a step)
		var probe := terrain_contact and not (_far and not is_local) and is_inside_tree()
		if probe != foot_lock.ground_probe.is_valid():
			foot_lock.ground_probe = _probe_ground if probe else Callable()
		foot_lock.phase = fposmod(_phase, 1.0)
		foot_lock.duty = _duty(_bs)
	# footsteps at the gait's own foot strikes (left at 1 - duty/2, right at
	# 0.5 - duty/2 of the cycle): the sound is where the foot meets the ground
	var duty := _duty(_bs)
	var k := int(floor((_phase + duty * 0.5) * 2.0))
	if not _step_init:
		_step_k = k   # start counting from the current phase (no phantom step)
		_step_init = true
	if k != _step_k:
		if on_floor and speed > 1.0 and k > _step_k and _near_camera(30.0):
			var walk := speed < 3.0
			var db := (-12.0 if walk else -6.0) + (4.0 if sprinting else 0.0) + (2.0 if role == TC.Role.PATROL else 0.0)
			Sfx.play("step", global_position, db, 0.9 if role == TC.Role.PATROL else 1.1)
		_step_k = k
	# turn in place
	if speed < 0.4:
		_yaw_accum += yaw_rate * delta
		_yaw_accum *= exp(-delta * 4.0)
		if absf(_yaw_accum) > 0.5 and _turn_cd <= 0.0:
			tree.set("parameters/turn_dir/transition_request", "l" if _yaw_accum > 0.0 else "r")
			tree.set("parameters/turn/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)
			_turn_cd = 0.45
			_yaw_accum = 0.0
	else:
		_yaw_accum = 0.0
	# idle fidgets (menus: restrained ones, more often)
	var fid_on := bool(tree.get("parameters/fidget/active"))
	if not fid_on:
		_fidget_on = false
	if fidgets and speed < 0.1 and _move_w < 0.05 and float(rs.get("emote_t", 0.0)) <= 0.0 and _arrive_t <= 0.0 and _ready_t <= 0.0:
		_still_t += delta
		if _still_t > _next_fidget and not fid_on:
			_still_t = 0.0
			var pool: Dictionary = MENU_FIDGETS if menu_idle else GAME_FIDGETS
			_next_fidget = _rng.randf_range(7.0, 12.0) if menu_idle else _rng.randf_range(8.0, 16.0)
			_fidget = _pick(pool)
			tree.set("parameters/fidget_pick/transition_request", _fidget)
			tree.set("parameters/fidget/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)
			_fidget_on = true
	else:
		_still_t = 0.0
		if _fidget_on and speed > 0.3:
			tree.set("parameters/fidget/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FADE_OUT)
			_fidget_on = false


func _pick(pool: Dictionary) -> String:
	var tot := 0.0
	for k in pool:
		tot += float(pool[k])
	var r := _rng.randf() * tot
	for k in pool:
		r -= float(pool[k])
		if r <= 0.0:
			return k
	return pool.keys()[0]


func _land(fall_speed: float, speed: float) -> void:
	_since_land = 0.0
	var hard := clampf(inverse_lerp(4.0, 11.0, fall_speed), 0.0, 1.0)
	var which := "u" if speed > 1.5 else "f"
	# the impact starts from the pose on screen (arms still up from the fall)
	_fade_from_shown(0.09)
	tree.set("parameters/land_mix_%s/blend_amount" % which, hard)
	tree.set("parameters/land_%s/request" % which, AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)
	_squash_v += clampf(fall_speed * 0.32, 1.0, 3.6) * (0.6 if speed > 1.5 else 1.0)
	if _near_camera(25.0):
		Sfx.play("land", global_position, -8.0 + 5.0 * hard)


## Splash choreography clock: starts at the authoritative state_t (so a late
## joiner enters at the right beat), advances with real frame time between
## snapshots and re-syncs if it drifts.
func _update_splash(delta: float, state_t: float, entered: bool) -> void:
	if entered or _splash_t < 0.0:
		_splash_t = state_t
		_splash_beats = 0
		_splash_pos = global_position
		_splash_kind = clampi(int(rs.get("impact", 0)), 0, IMPACTS.size() - 1)
		tree.set("parameters/splash_kind/transition_request", str(_splash_kind))
		_set_wet(1.0)
	else:
		_splash_t += delta
		if absf(_splash_t - state_t) > 0.15:
			_splash_t = state_t
	var t := clampf(_splash_t, 0.0, SPLASH_LEN)
	tree.set("parameters/splash_seek/seek_request", t)
	_splash_beat_fx(t)


## Splash FX beats, each at most once per splash.  A late joiner who first
## sees the runner mid-sequence skips the beats that already happened.
func _splash_beat_fx(t: float) -> void:
	if fx == null or not visible:
		return
	var w: Dictionary = water_at.call(_splash_pos) if water_at.is_valid() else {}
	var beats := [
		[0, 0.0, 0.25], [1, 0.42, 0.6], [2, 0.75, 0.95], [3, 1.02, 1.2], [4, 1.36, 1.5],
	]
	for b in beats:
		var bit := 1 << int(b[0])
		if (_splash_beats & bit) != 0 or t < float(b[1]):
			continue
		_splash_beats |= bit
		if t > float(b[2]):
			continue   # joined after this beat
		match int(b[0]):
			0:
				fx.splash_impact(_splash_pos, _splash_kind, w.get("color", Color(0.6, 0.85, 1.0)), reduced_motion)
				fx.ripple(w, _splash_pos, 1.0)
				if _near_camera(40.0):
					Sfx.play("splash_big" if bool(rs.get("stamped", false)) else "splash", _splash_pos)
			1:
				fx.ripple(w, _splash_pos, 0.55)
			2, 3:
				fx.ripple(w, _splash_pos, 0.3)
			4:
				fx.ripple(w, _splash_pos, 0.6)
				fx.duck_under(_splash_pos, reduced_motion)


func _on_resurface() -> void:
	tree.set("parameters/recover/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)
	_set_wet(1.0)
	_ensure_drips()
	_drip_t = 1.4 if not reduced_motion else 0.8
	if fx and visible:
		fx.shore_pop(global_position, reduced_motion)


func _m_per_cycle(bs: float) -> float:
	if bs <= LOCO_POINTS["run"]:
		return lerpf(LOCO_M_PER_CYCLE["walk"], LOCO_M_PER_CYCLE["run"], inverse_lerp(LOCO_POINTS["walk"], LOCO_POINTS["run"], bs))
	return lerpf(LOCO_M_PER_CYCLE["run"], LOCO_M_PER_CYCLE["sprint"], inverse_lerp(LOCO_POINTS["run"], LOCO_POINTS["sprint"], bs))


func _duty(bs: float) -> float:
	if bs <= LOCO_POINTS["run"]:
		return lerpf(LOCO_DUTY["walk"], LOCO_DUTY["run"], inverse_lerp(LOCO_POINTS["walk"], LOCO_POINTS["run"], bs))
	return lerpf(LOCO_DUTY["run"], LOCO_DUTY["sprint"], inverse_lerp(LOCO_POINTS["run"], LOCO_POINTS["sprint"], bs))


## Gait cycles per second at a ground speed (for tests and tools).
static func gait_rate(speed: float) -> float:
	var v := CharacterView.new()
	var bs := clampf(speed, LOCO_POINTS["walk"], LOCO_POINTS["sprint"])
	var r := speed / v._m_per_cycle(bs)
	v.free()
	return r


func _update_face(delta: float, m: String, sprinting: bool, tag_phase: int, spotted: bool) -> void:
	var tgt := {"blink": 0.0, "squint": 0.0, "smile": 0.0, "open": 0.0, "brow_up": 0.0, "brow_angry": 0.0}
	match m:
		"celebrate", "emote_cheer", "emote_laugh", "emote_dance", "arrive", "ready", "emote_victory_lap":
			tgt["squint"] = 1.0
			tgt["smile"] = 1.0
			tgt["open"] = 0.55
		"splash":
			# surprise on impact, puffed-cheek calm while treading, a breath before ducking
			var t := _splash_t
			if t < 0.45:
				tgt["open"] = 0.9
				tgt["brow_up"] = 1.0
			elif t < 1.15:
				tgt["smile"] = 0.3
				tgt["brow_up"] = 0.4
			else:
				tgt["open"] = 0.7
				tgt["squint"] = 0.6
		"air":
			var vy := float((rs.get("vel", Vector3.ZERO) as Vector3).y)
			tgt["open"] = 0.5 if vy < -4.0 else 0.2
			tgt["smile"] = 0.5 if vy > 0.0 else 0.0
			tgt["brow_up"] = 0.6 if vy < -4.0 else 0.2
		"stumble", "flop":
			tgt["open"] = 0.85
			tgt["brow_up"] = 1.0
		"dizzy":
			tgt["squint"] = 0.6
			tgt["open"] = 0.3
			tgt["brow_up"] = 0.5
		"tag_windup", "tag_lunge", "dive":
			tgt["brow_angry"] = 1.0
			tgt["open"] = 0.35
		"tag_miss":
			tgt["brow_up"] = 0.9
			tgt["open"] = 0.5
		"emote_wave", "emote_point":
			tgt["smile"] = 0.9
			tgt["open"] = 0.3
		"emote_shrug":
			tgt["brow_up"] = 0.8
		"emote_stargaze":
			# wonder: lifted brows, a soft open smile
			tgt["smile"] = 0.6
			tgt["brow_up"] = 0.7
			tgt["open"] = 0.3
		"emote_shush":
			# sly: half-closed eyes, a small smile
			tgt["squint"] = 0.55
			tgt["smile"] = 0.3
			tgt["brow_up"] = 0.35
		"emote_moon_shuffle":
			# cool: easy smile, relaxed lids
			tgt["smile"] = 0.85
			tgt["squint"] = 0.6
			tgt["open"] = 0.15
		_:
			tgt["smile"] = 0.35
			if sprinting or tag_phase > 0:
				tgt["brow_angry"] = 0.8
				tgt["smile"] = 0.0
	if _fidget_on and _fidget == "fidget_yawn":
		tgt["open"] = 0.8
		tgt["squint"] = 0.7
	elif _fidget_on and _fidget == "fidget_bounce":
		tgt["smile"] = 0.6
	if _drip_t > 0.0:
		tgt["squint"] = maxf(float(tgt["squint"]), 0.7)
	if spotted:
		tgt["brow_up"] = 1.0
		tgt["open"] = maxf(float(tgt["open"]), 0.6)
		tgt["smile"] = 0.0
	# blinking (never while squinting): a quick close and a softer open; in
	# menus slower, softer and now and then a double blink
	_blink_t -= delta
	if _blink_t <= 0.0:
		if menu_idle and _rng.randf() < 0.2:
			_blink_t = 0.3
		else:
			_blink_t = _rng.randf_range(2.6, 5.2) if menu_idle else _rng.randf_range(2.2, 4.6)
		_blink_len = 0.2 if menu_idle else 0.15
		_blink = _blink_len
	_blink = maxf(0.0, _blink - delta)
	var bw := 0.0
	if _blink > 0.0:
		var u := 1.0 - _blink / _blink_len      # 0 -> 1 over the blink
		bw = smoothstep(0.0, 0.3, u) * (1.0 - smoothstep(0.45, 1.0, u))
	if float(tgt["squint"]) < 0.5:
		tgt["blink"] = bw
	var k := 1.0 - exp(-delta * 18.0)
	for key in _face:
		var target: float = float(tgt.get(key, 0.0))
		var cur := float(_face[key])
		_face[key] = target if key == "blink" else lerpf(cur, target, k)
		var w := minf(1.0, float(_face[key]) + float(_face_base.get(key, 0.0)))
		if _face_idx.has(key):
			face_mesh.set_blend_shape_value(_face_idx[key], w)


func _camera_distance() -> float:
	var cam := get_viewport().get_camera_3d() if is_inside_tree() else null
	return cam.global_position.distance_to(global_position) if cam != null else INF


## Uses this frame's camera distance (measured once at the top of _process).
func _near_camera(r: float) -> bool:
	return _cam_d < r
