#!/usr/bin/env python3
"""Writes the Shop's rotating-offer schedule into game/config/catalogue.json
("offers" -> "schedule") from the explicit rule beside it ("offers" -> "rule").

The rule (Pass 8, docs/ECONOMY.md section 2.1):
  - `slots` Featured slots (4), each offer lasts exactly `offer_hours` (48 h),
    every change is at a 00:00 UTC day boundary.
  - Slots are staggered by `slot_phase_days` ([0, 0, 1, 1]): slots 1-2 change
    on even days from `start_utc`, slots 3-4 on odd days, so two offers
    change every day.  Slots 3-4 open their first offer one day before
    `start_utc`, so every offer, including the first, is a full 48 h.
  - The pool is every catalogue item with "rotation": true, in catalogue
    order.  At each change, each changing slot (in slot order) takes the pool
    item that left the Shop longest ago (never shown counts as longest; ties
    in catalogue order) among those not on show in another slot, not chosen
    for another slot at the same moment and not leaving at that moment.  So
    a skin is never shown twice at once and never comes straight back.
  - Offers are generated for change days from (start - 1 day) up to
    `start_utc + days`; the last ones end up to a day later.
  - Price = the item's catalogue Coin price (no sale prices).
  - offer_id = "r<revision>-<YYYYMMDD of start>-s<slot>": unique and never
    reused.  An existing offer with the same slot, times, item and price keeps
    its id (so an extension or a revision leaves published offers alone).

Published offers are history: writing refuses to change or drop an offer
that started before --now (default: the current time) unless --force.

Usage:
  python3 tools/make_offer_schedule.py            # regenerate and write
  python3 tools/make_offer_schedule.py --check    # exit 1 if the file differs
  python3 tools/make_offer_schedule.py --now=2026-11-01T00:00:00Z
Then run `node service/tools/sync_catalogue.mjs` (the service's copy).
"""
import datetime as dt
import json
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
PATH = os.path.join(ROOT, "game", "config", "catalogue.json")
DAY = dt.timedelta(days=1)
DEFAULT_COMMENT = ("Pass 8 rotating Shop offers. GENERATED by tools/make_offer_schedule.py from 'rule' and the items with "
                   "\"rotation\": true: edit the rule (or the pool), bump schedule_revision, run the tool, then node "
                   "service/tools/sync_catalogue.mjs. An offer (offer_id) sells one permanent item (item_id) for its Coin price "
                   "between starts_at_utc (inclusive) and ends_at_utc (exclusive), judged by the game service's clock at the "
                   "moment it accepts the purchase. Ownership never expires; a skin can return under a new offer_id.")


def iso(t):
    return t.strftime("%Y-%m-%dT%H:%M:%SZ")


def parse(s):
    return dt.datetime.strptime(s, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=dt.timezone.utc)


def pool_of(cat):
    return [it for it in cat["items"] if it.get("rotation") is True]


def generate(cat):
    off = cat["offers"]
    rule = off["rule"]
    rev = int(off.get("schedule_revision", 1))
    start = parse(rule["start_utc"])
    assert start.hour == 0 and start.minute == 0 and start.second == 0, "start_utc must be 00:00 UTC"
    hours = int(rule["offer_hours"])
    assert hours % 24 == 0 and hours >= 48, "offers last whole days, at least 48 h"
    span = hours // 24
    slots = int(rule["slots"])
    phase = [int(p) for p in rule["slot_phase_days"]]
    assert len(phase) == slots
    pool = pool_of(cat)
    assert len(pool) >= slots + 2, "the pool needs more skins than slots (plus the two leaving)"
    order = {it["id"]: i for i, it in enumerate(pool)}
    price = {it["id"]: int(it["price"]) for it in pool}
    left_at = {it["id"]: None for it in pool}      # when it last left the Shop
    showing = {}                                    # slot -> (item, ends)
    keep = {}
    for o in off.get("schedule", []):
        keep[(o["slot"], o["starts_at_utc"], o["ends_at_utc"], o["item_id"], o["price"])] = o["offer_id"]
    out = []
    first = min(phase)
    for d in range(first - 1, int(rule["days"])):
        t = start + d * DAY
        changing = [s for s in range(slots) if (d - phase[s]) % span == 0]
        if not changing:
            continue
        leaving = {showing[s][0] for s in changing if s in showing}
        for s in changing:
            if s in showing:
                left_at[showing[s][0]] = t
                del showing[s]
        busy = {v[0] for v in showing.values()}
        for s in changing:
            cands = [i for i in order if i not in busy and i not in leaving]
            cands.sort(key=lambda i: (left_at[i] is not None, left_at[i] or t, order[i]))
            pick = cands[0]
            busy.add(pick)
            ends = t + span * DAY
            showing[s] = (pick, ends)
            a, b = iso(t), iso(ends)
            oid = keep.get((s + 1, a, b, pick, price[pick])) or "r%d-%s-s%d" % (rev, t.strftime("%Y%m%d"), s + 1)
            out.append({"offer_id": oid, "item_id": pick, "slot": s + 1, "starts_at_utc": a, "ends_at_utc": b,
                        "price": price[pick], "revision": rev})
    out.sort(key=lambda o: (o["starts_at_utc"], o["slot"]))
    return out


def render_section(cat, schedule):
    off = cat["offers"]
    lines = ['  "offers": {']
    lines.append('    "_comment": %s,' % json.dumps(off.get("_comment") or DEFAULT_COMMENT))
    lines.append('    "schedule_revision": %d,' % int(off.get("schedule_revision", 1)))
    lines.append('    "rule": %s,' % json.dumps(off["rule"]))
    lines.append('    "schedule": [')
    for i, o in enumerate(schedule):
        lines.append("      " + json.dumps(o) + ("," if i < len(schedule) - 1 else ""))
    lines.append("    ]")
    lines.append("  },")
    return "\n".join(lines) + "\n"


def splice(text, section):
    m = re.search(r'^  "offers": \{\n', text, re.M)
    assert m, 'no "offers" section in catalogue.json'
    i = m.end()
    depth = 1
    while depth:
        c = text[i]
        depth += c == "{"
        depth -= c == "}"
        i += 1
    if text[i] == ",":
        i += 1
    if text[i] == "\n":
        i += 1
    return text[:m.start()] + section + text[i:]


def main(argv):
    text = open(PATH, encoding="utf-8").read()
    cat = json.loads(text)
    now = dt.datetime.now(dt.timezone.utc)
    for a in argv:
        if a.startswith("--now="):
            now = parse(a.split("=", 1)[1])
    schedule = generate(cat)
    new_text = splice(text, render_section(cat, schedule))
    json.loads(new_text)
    if "--check" in argv:
        if new_text != text:
            print("catalogue.json offers.schedule is stale: run python3 tools/make_offer_schedule.py")
            return 1
        print("offer schedule up to date (%d offers)" % len(schedule))
        return 0
    if "--force" not in argv:
        fresh = {o["offer_id"]: o for o in schedule}
        for o in cat["offers"].get("schedule", []):
            if parse(o["starts_at_utc"]) <= now and fresh.get(o["offer_id"]) != o:
                print("refusing: published offer %s (started %s) would change; use --force only before release" % (o["offer_id"], o["starts_at_utc"]))
                return 2
    open(PATH, "w", encoding="utf-8").write(new_text)
    print("wrote %d offers (%s .. %s) into %s" % (len(schedule), schedule[0]["starts_at_utc"], schedule[-1]["ends_at_utc"],
                                                  os.path.relpath(PATH, ROOT)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
